"""HSL-based colour ramp generator.

Generates a 12-shade ramp from any hex colour using the Tailwind/Untitled UI
shade scale (25, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950).

Uses only stdlib ``colorsys`` -- no external dependencies.
"""

from __future__ import annotations

import colorsys


def hex_to_hsl(hex_color: str) -> tuple[float, float, float]:
    """Convert a hex colour string to HSL (hue, saturation, lightness).

    Parameters
    ----------
    hex_color : str
        Hex colour like ``"#6366F1"`` or ``"6366F1"``.

    Returns
    -------
    tuple[float, float, float]
        (h, s, l) where h is in [0, 1] and s, l are in [0, 1].
    """
    hex_color = hex_color.lstrip("#")
    r, g, b = (int(hex_color[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
    # colorsys uses HLS order (hue, lightness, saturation)
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return h, s, l


def hsl_to_hex(h: float, s: float, l: float) -> str:
    """Convert HSL values back to a hex colour string.

    Parameters
    ----------
    h : float
        Hue in [0, 1].
    s : float
        Saturation in [0, 1].
    l : float
        Lightness in [0, 1].

    Returns
    -------
    str
        Hex colour string like ``"#6366F1"``.
    """
    # colorsys expects HLS order
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    return "#{:02X}{:02X}{:02X}".format(
        round(r * 255), round(g * 255), round(b * 255),
    )


def generate_ramp(hex_color: str) -> dict[int, str]:
    """Generate a 12-shade ramp from a single hex colour.

    Shade 500 is the input colour (preserved exactly). Lighter shades
    (25--400) and darker shades (600--950) are generated by interpolating
    lightness in HSL space, with slight desaturation at the extremes for
    a natural feel.

    Returns
    -------
    dict[int, str]
        Mapping of shade number to hex string.
    """
    h, s, l = hex_to_hsl(hex_color)

    # Target lightness for each shade (empirically tuned to match Untitled UI)
    targets: dict[int, float] = {
        25:  0.97,
        50:  0.94,
        100: 0.88,
        200: 0.78,
        300: 0.66,
        400: 0.55,
        500: l,       # preserve original lightness
        600: 0.38,
        700: 0.30,
        800: 0.23,
        900: 0.17,
        950: 0.11,
    }

    ramp: dict[int, str] = {}
    for shade, target_l in targets.items():
        if shade == 500:
            ramp[shade] = hex_color
        else:
            # Reduce saturation at light/dark extremes for natural feel
            sat_factor = 1.0 - 0.3 * abs(target_l - 0.5)
            adj_s = s * sat_factor
            ramp[shade] = hsl_to_hex(h, adj_s, target_l)

    return ramp
