"""Typst document renderer — generates A4/Letter report markup.

Produces branded documents with:
- Cover page with logo + title block
- Auto-generated TOC with heading numbering
- Branded headers (logo + doc title) and footers (confidentiality + page numbers)
- Dark header tables with alternating row fills
- Callout boxes, RAG badges, source notes
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from inkline.typst.components import _rgb


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class DocumentSpec:
    """Specification for a branded document."""
    title: str = ""
    subtitle: str = ""
    date: str = ""
    author: str = ""
    sections: list[dict[str, Any]] = field(default_factory=list)
    paper: str = "a4"  # "a4" or "us-letter"


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------

class TypstDocumentRenderer:
    """Renders DocumentSpec to Typst markup for A4/Letter reports."""

    def __init__(self, theme: dict):
        self.t = theme

    def render_document(self, spec: DocumentSpec) -> str:
        """Render a full document to Typst source."""
        parts = [
            self._preamble(spec),
            self._heading_styles(),
            self._component_defs(),
            self._cover_page(spec),
            self._toc_page(),
        ]

        for section in spec.sections:
            parts.append(self._render_section(section))

        return "\n\n".join(parts)

    def render_from_markdown(self, markdown: str, spec: DocumentSpec) -> str:
        """Render a document from Markdown content.

        Converts Markdown headings, lists, bold, italic, and tables to
        Typst markup, then wraps in branded document chrome.
        """
        parts = [
            self._preamble(spec),
            self._heading_styles(),
            self._component_defs(),
            self._cover_page(spec),
            self._toc_page(),
            self._markdown_to_typst(markdown),
        ]
        return "\n\n".join(parts)

    # -- Preamble ----------------------------------------------------------

    def _preamble(self, spec: DocumentSpec) -> str:
        t = self.t
        heading_font = t.get("heading_font", "Inter")
        body_font = t.get("body_font", "Inter")
        body_size = t.get("body_size", 11)
        accent = t.get("accent", "#1a3a5c")
        muted = t.get("muted", "#6B7280")
        border = t.get("border", "#D1D5DB")
        conf = t.get("confidentiality", "")
        footer_text = t.get("footer_text", "")
        doc_title = _esc(spec.title)
        date = _esc(spec.date)

        return f"""// Generated by Inkline - Typst Document Engine
#set page(
  paper: "{spec.paper}",
  fill: white,
  margin: (top: 3cm, bottom: 2.5cm, left: 2.5cm, right: 2.5cm),
  header: context {{
    if counter(page).get().first() > 1 {{
      grid(
        columns: (1fr, 1fr),
        text(font: "{heading_font}", weight: "bold", size: 9pt, fill: {_rgb(accent)})[{doc_title}],
        align(right, text(size: 8pt, fill: {_rgb(muted)})[{_esc(conf)}]),
      )
      v(4pt)
      line(length: 100%, stroke: 0.5pt + {_rgb(border)})
    }}
  }},
  footer: context {{
    line(length: 100%, stroke: 0.3pt + {_rgb(border)})
    v(4pt)
    grid(
      columns: (1fr, 1fr),
      text(size: 7pt, fill: {_rgb(muted)})[{_esc(footer_text)} - {date}],
      align(right, text(size: 8pt, fill: {_rgb(muted)})[Page #counter(page).display() of #context counter(page).final().first()]),
    )
  }},
)

#set text(font: "{body_font}", size: {body_size}pt, fill: {_rgb(t.get('text', '#1A1A1A'))})
#set par(leading: 0.8em, justify: true)
#set table(stroke: 0.5pt + {_rgb(border)}, inset: 6pt)"""

    # -- Heading styles ----------------------------------------------------

    def _heading_styles(self) -> str:
        t = self.t
        accent = t.get("accent", "#1a3a5c")
        accent2 = t.get("accent2", "#39d3bb")
        heading_font = t.get("heading_font", "Inter")
        text_color = t.get("text", "#1A1A1A")

        return f"""// Heading styles
#set heading(numbering: "1.1")

#show heading.where(level: 1): it => {{
  v(16pt)
  text(font: "{heading_font}", weight: "bold", size: 18pt, fill: {_rgb(accent)})[#it]
  v(4pt)
  line(length: 100%, stroke: 1pt + {_rgb(accent2)})
  v(8pt)
}}

#show heading.where(level: 2): it => {{
  v(12pt)
  text(font: "{heading_font}", weight: "bold", size: 14pt, fill: {_rgb(accent)})[#it]
  v(6pt)
}}

#show heading.where(level: 3): it => {{
  v(8pt)
  text(font: "{heading_font}", weight: "bold", size: 12pt, fill: {_rgb(text_color)})[#it]
  v(4pt)
}}"""

    # -- Component definitions ---------------------------------------------

    def _component_defs(self) -> str:
        t = self.t
        accent = t.get("accent", "#1a3a5c")
        accent2 = t.get("accent2", "#39d3bb")
        muted = t.get("muted", "#6B7280")
        bg = t.get("bg", "#FFFFFF")
        light_bg = t.get("surface", "#F4F6F8")
        border = t.get("border", "#D1D5DB")

        return f"""// Reusable components
#let rag-badge(status) = {{
  let color = if status == "RED" {{ rgb("#dc2626") }} else if status == "AMBER" {{ rgb("#f59e0b") }} else if status == "GREEN" {{ rgb("#10b981") }} else {{ rgb("#6b7280") }}
  box(fill: color, radius: 2pt, inset: (x: 6pt, y: 2pt), text(size: 8pt, weight: "bold", fill: white)[#upper(status)])
}}

#let callout(title, body, color: {_rgb(accent)}) = {{
  block(
    width: 100%,
    inset: (left: 14pt, rest: 10pt),
    stroke: (left: 3pt + color),
    fill: {_rgb(light_bg)},
    radius: (right: 4pt),
  )[
    #text(weight: "bold", fill: color)[#title]
    #v(4pt)
    #body
  ]
}}

#let source-note(content) = {{
  text(size: 8pt, style: "italic", fill: {_rgb(muted)})[Source: #content]
}}

#let metric-box(value, label) = {{
  align(center)[
    #text(weight: "bold", size: 24pt, fill: {_rgb(accent)})[#value]
    #v(2pt)
    #text(size: 9pt, fill: {_rgb(muted)})[#upper(label)]
  ]
}}"""

    # -- Cover page --------------------------------------------------------

    def _cover_page(self, spec: DocumentSpec) -> str:
        t = self.t
        accent = t.get("accent", "#1a3a5c")
        accent2 = t.get("accent2", "#39d3bb")
        muted = t.get("muted", "#6B7280")
        heading_font = t.get("heading_font", "Inter")
        conf = t.get("confidentiality", "")

        # Try to use shield logo if available, else full logo
        logo_markup = ""
        logo_path = t.get("logo_light_path", "")
        if logo_path:
            # We'll use the logo name as-is — the caller must ensure the file
            # is accessible from the Typst root directory
            logo_markup = f'#image("{logo_path}", width: 5cm)'

        return f"""// Cover page
#set page(header: none, footer: none)

#v(3cm)
#align(center)[
  {logo_markup}
  #v(1cm)
  #line(length: 60%, stroke: 2pt + {_rgb(accent2)})
  #v(0.8cm)
  #text(font: "{heading_font}", weight: "bold", size: 28pt, fill: {_rgb(accent)})[
    #upper("{_esc(spec.title)}")
  ]
  #v(0.4cm)
  #text(size: 14pt, fill: {_rgb(muted)})[{_esc(spec.subtitle)}]
  #v(1cm)
  #text(size: 12pt, fill: {_rgb(muted)})[{_esc(spec.date)}]
  #v(0.3cm)
  #text(size: 11pt, fill: {_rgb(muted)})[{_esc(spec.author)}]
]

#v(1fr)
#align(center, text(size: 9pt, fill: {_rgb(muted)})[{_esc(conf)}])

#pagebreak()"""

    # -- TOC ---------------------------------------------------------------

    def _toc_page(self) -> str:
        t = self.t
        accent = t.get("accent", "#1a3a5c")
        heading_font = t.get("heading_font", "Inter")

        return f"""// Table of Contents
#set page(header: auto, footer: auto)
#counter(page).update(1)

#text(font: "{heading_font}", weight: "bold", size: 18pt, fill: {_rgb(accent)})[Table of Contents]
#v(8pt)
#outline(indent: 1.5em, depth: 2)

#pagebreak()"""

    # -- Section rendering -------------------------------------------------

    def _render_section(self, section: dict) -> str:
        """Render a document section.

        Section dict keys:
        - heading: str — section heading text
        - level: int — heading level (1, 2, 3)
        - content: str — body text (Typst markup)
        - pagebreak: bool — add pagebreak after section
        """
        level = section.get("level", 1)
        heading = section.get("heading", "")
        content = section.get("content", "")
        pb = section.get("pagebreak", False)

        heading_prefix = "=" * level
        parts = [f"{heading_prefix} {heading}"]
        if content:
            parts.append(content)
        if pb:
            parts.append("#pagebreak()")

        return "\n\n".join(parts)

    # -- Markdown to Typst conversion (basic) ------------------------------

    def _markdown_to_typst(self, md: str) -> str:
        """Convert basic Markdown to Typst markup.

        Handles: headings, bold, italic, bullet lists, numbered lists,
        horizontal rules, and basic tables.
        """
        lines = md.split("\n")
        output = []
        in_table = False
        table_rows: list[list[str]] = []
        in_code = False
        code_buffer: list[str] = []
        code_lang = ""

        for line in lines:
            stripped = line.strip()

            # Fenced code blocks (```lang ... ```)
            if stripped.startswith("```"):
                if in_code:
                    # Closing fence — emit raw block.
                    # Pass raw() as a positional arg to block() to avoid
                    # Typst's content-mode [...] parsing the string contents
                    # (which would treat @, # etc. as syntax inside the body).
                    code_text = "\n".join(code_buffer)
                    escaped = (
                        code_text
                        .replace("\\", "\\\\")
                        .replace("\"", "\\\"")
                        .replace("\n", "\\n")
                    )
                    if code_lang:
                        raw_call = f'raw(lang: "{code_lang}", block: true, "{escaped}")'
                    else:
                        raw_call = f'raw(block: true, "{escaped}")'
                    output.append(
                        f'#block(fill: rgb("#F5F5F5"), inset: 8pt, radius: 3pt, '
                        f'width: 100%, {raw_call})'
                    )
                    code_buffer = []
                    code_lang = ""
                    in_code = False
                else:
                    # Opening fence
                    code_lang = stripped[3:].strip()
                    in_code = True
                continue

            if in_code:
                code_buffer.append(line)
                continue

            # Flush table if we leave table context
            if in_table and not stripped.startswith("|"):
                output.append(self._flush_table(table_rows))
                table_rows = []
                in_table = False

            # Headings — any number of # followed by space
            heading_match = re.match(r"^(#{1,6})\s+(.*)$", stripped)
            if heading_match:
                level = len(heading_match.group(1))
                text = self._inline_format(heading_match.group(2))
                output.append(f'{"=" * level} {text}')
                continue

            # Horizontal rule
            if stripped in ("---", "***", "___"):
                output.append("#line(length: 100%)")
                continue

            # Table rows
            if stripped.startswith("|"):
                cells = [c.strip() for c in stripped.strip("|").split("|")]
                if all(set(c) <= set("-: ") for c in cells):
                    continue  # Skip separator row
                table_rows.append(cells)
                in_table = True
                continue

            # Bullet lists
            if stripped.startswith("- ") or stripped.startswith("* "):
                text = stripped[2:]
                text = self._inline_format(text)
                output.append(f"- {text}")
                continue

            # Numbered lists
            match = re.match(r"^(\d+)\.\s+(.*)", stripped)
            if match:
                text = self._inline_format(match.group(2))
                output.append(f"+ {text}")
                continue

            # Regular paragraph
            output.append(self._inline_format(stripped))

        # Flush remaining table
        if in_table:
            output.append(self._flush_table(table_rows))

        return "\n".join(output)

    def _inline_format(self, text: str) -> str:
        """Convert inline Markdown formatting to Typst."""
        # First escape Typst-special characters that aren't markdown syntax:
        #   $ → math mode
        #   @ → label reference
        #   < → label declaration (e.g. <2 seconds is parsed as unclosed label)
        #   > → end of label / heading marker in some contexts
        # Done BEFORE markdown processing so they survive to output.
        text = text.replace("$", "\\$")
        text = text.replace("@", "\\@")
        text = text.replace("<", "\\<")
        text = text.replace(">", "\\>")
        # Don't escape # here because we want #raw() etc. to work in headers
        # Bold
        text = re.sub(r"\*\*(.+?)\*\*", r"*\1*", text)
        text = re.sub(r"__(.+?)__", r"*\1*", text)
        # Italic
        text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"_\1_", text)
        text = re.sub(r"(?<!_)_(?!_)(.+?)(?<!_)_(?!_)", r"_\1_", text)
        # Inline code
        text = re.sub(r"`(.+?)`", r'#raw("\1")', text)
        return text

    def _flush_table(self, rows: list[list[str]]) -> str:
        """Convert accumulated table rows to a Typst table."""
        if not rows:
            return ""
        t = self.t
        n_cols = max(len(r) for r in rows)
        accent = t.get("accent", "#1a3a5c")
        border = t.get("border", "#D1D5DB")
        bg = t.get("surface", "#F4F6F8")

        header_cells = ",\n    ".join(
            f'table.cell(fill: {_rgb(accent)})[#text(fill: white, weight: "bold", size: 9pt)[{self._inline_format(cell)}]]'
            for cell in rows[0]
        )

        data_cells = []
        for row in rows[1:]:
            for cell in row:
                data_cells.append(f"[{self._inline_format(cell)}]")
        data_str = ", ".join(data_cells)

        widths = ", ".join(["1fr"] * n_cols)

        return f"""#block(width: 100%)[
  #set par(justify: false)
  #table(
    columns: ({widths}),
    inset: 6pt,
    stroke: 0.5pt + {_rgb(border)},
    fill: (_, y) => if y == 0 {{ {_rgb(accent)} }} else if calc.odd(y) {{ white }} else {{ {_rgb(bg)} }},
    {header_cells},
    {data_str},
  )
]"""


def _esc(text: str) -> str:
    """Escape special Typst characters."""
    if not text:
        return ""
    return (
        text
        .replace("\\", "\\\\")
        .replace("#", "\\#")
        .replace("$", "\\$")
        .replace("@", "\\@")
        .replace("<", "\\<")
        .replace(">", "\\>")
    )
