"""Typst slide renderer — generates 16:9 presentation markup from structured data.

Produces a complete ``.typ`` source string that compiles to a multi-page PDF
where each page is one slide.

Slide types: title, content, three_card, four_card, stat, table, split,
chart, closing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from inkline.typst.components import (
    _rgb,
    accent_bar,
    bar_row,
    card,
    card_title,
    data_table,
    footer_bar,
    hero_stat,
    section_badge,
    slide_title,
)


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class SlideSpec:
    """Specification for a single slide."""
    slide_type: str  # title, content, three_card, four_card, stat, table, split, chart, closing
    data: dict[str, Any] = field(default_factory=dict)


@dataclass
class DeckSpec:
    """Specification for a full slide deck."""
    slides: list[SlideSpec] = field(default_factory=list)
    title: str = "Untitled"
    date: str = ""
    subtitle: str = ""


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------

class TypstSlideRenderer:
    """Renders SlideSpec objects into Typst markup."""

    def __init__(self, theme: dict):
        self.t = theme

    def render_deck(self, spec: DeckSpec) -> str:
        """Render a full deck to Typst source."""
        parts = [self._preamble()]
        for i, slide in enumerate(spec.slides):
            if i > 0:
                parts.append("#pagebreak()")
            parts.append(self._render_slide(slide))
        return "\n\n".join(parts)

    # -- Preamble ----------------------------------------------------------

    def _preamble(self) -> str:
        t = self.t
        heading_font = t.get("heading_font", "Inter")
        body_font = t.get("body_font", "Inter")
        body_size = t.get("body_size", 11)
        return f"""// Generated by Inkline - Typst Slide Engine
#set page(width: 25.4cm, height: 14.29cm, margin: (x: 1.2cm, y: 0.8cm))
#set text(font: "{body_font}", size: {body_size}pt)
#set par(leading: 0.7em)"""

    # -- Slide dispatch ----------------------------------------------------

    def _render_slide(self, slide: SlideSpec) -> str:
        renderer = {
            "title": self._title_slide,
            "content": self._content_slide,
            "three_card": self._three_card_slide,
            "four_card": self._four_card_slide,
            "stat": self._stat_slide,
            "table": self._table_slide,
            "split": self._split_slide,
            "chart": self._chart_slide,
            "closing": self._closing_slide,
            "bar_chart": self._bar_chart_slide,
            "kpi_strip": self._kpi_strip_slide,
            "timeline": self._timeline_slide,
            "process_flow": self._process_flow_slide,
            "icon_stat": self._icon_stat_slide,
            "progress_bars": self._progress_bars_slide,
            "pyramid": self._pyramid_slide,
            "comparison": self._comparison_slide,
        }.get(slide.slide_type)
        if not renderer:
            return f'// Unknown slide type: {slide.slide_type}'
        return renderer(slide.data)

    # -- Title slide -------------------------------------------------------

    def _title_slide(self, d: dict) -> str:
        t = self.t
        company = d.get("company", t.get("name", ""))
        tagline = d.get("tagline", "")
        date = d.get("date", "")
        subtitle = d.get("subtitle", "")
        desc = t.get("desc", "")
        conf = t.get("confidentiality", "")

        return f"""#{{
  set page(fill: {_rgb(t['title_bg'])})
  set text(fill: {_rgb(t['title_fg'])})

  {accent_bar(t['accent'], 'top')}

  v(1.5cm)
  text(size: 9pt, fill: {_rgb(t['muted'])})[#upper("{_esc(desc)}")]
  v(0.5cm)
  text(weight: "bold", size: 52pt, font: "{t.get('heading_font', 'Inter')}")[{_esc(company).upper()}]
  v(0.5cm)
  text(weight: "bold", size: 24pt, font: "{t.get('heading_font', 'Inter')}")[{_esc(tagline)}]
  {f'v(0.3cm){chr(10)}  text(size: 14pt, fill: {_rgb(t["muted"])})[{_esc(subtitle)}]' if subtitle else ''}
  v(1fr)
  line(length: 100%, stroke: 0.5pt + {_rgb(t['muted'])})
  v(4pt)
  grid(
    columns: (1fr, 1fr),
    text(weight: "bold", size: 11pt)[{_esc(d.get('left_footer', ''))}],
    align(right, text(size: 9pt, fill: {_rgb(t['muted'])})[{_esc(conf)} {_esc(date)}]),
  )
}}"""

    # -- Content slide -----------------------------------------------------

    def _content_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        items = d.get("items", [])
        footnote = d.get("footnote", "")

        bullets = "\n    ".join(f"- {_esc(item)}" for item in items)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  text(size: 12pt, fill: {_rgb(t['text'])})[
    {bullets}
  ]

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Three card slide --------------------------------------------------

    def _three_card_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        cards = d.get("cards", [])
        footnote = d.get("footnote", "")
        highlight_idx = d.get("highlight_index", 1)  # Which card gets accent fill

        card_markups = []
        for i, c in enumerate(cards[:3]):
            if i == highlight_idx:
                # Accent card
                cm = card(
                    f'{card_title(c.get("title", ""), t["title_fg"])}\n      #v(6pt)\n      #text(size: 10.5pt, fill: {_rgb(t["title_fg"])})[{_esc(c.get("body", ""))}]',
                    fill=t["accent"],
                    text_color=t["title_fg"],
                )
            else:
                cm = card(
                    f'{card_title(c.get("title", ""), t["text"])}\n      #v(6pt)\n      #text(size: 10.5pt, fill: {_rgb(t["muted"])})[{_esc(c.get("body", ""))}]',
                    fill=t["card_fill"],
                    border=t["border"],
                    text_color=t["text"],
                )
            card_markups.append(cm)

        cards_str = ",\n    ".join(card_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  grid(
    columns: (1fr, 1fr, 1fr),
    gutter: 14pt,
    {cards_str}
  )

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Four card slide ---------------------------------------------------

    def _four_card_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        cards = d.get("cards", [])
        footnote = d.get("footnote", "")

        card_markups = []
        for c in cards[:4]:
            cm = card(
                f'{card_title(c.get("title", ""), t["text"])}\n      #v(6pt)\n      #text(size: 10.5pt, fill: {_rgb(t["muted"])})[{_esc(c.get("body", ""))}]',
                fill=t["card_fill"],
                border=t["border"],
                text_color=t["text"],
            )
            card_markups.append(cm)

        cards_str = ",\n    ".join(card_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  grid(
    columns: (1fr, 1fr),
    gutter: 14pt,
    {cards_str}
  )

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Stat slide --------------------------------------------------------

    def _stat_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        stats = d.get("stats", [])

        stat_markups = []
        for i, s in enumerate(stats[:4]):
            accent = t["accent"] if i == 1 else None  # Highlight second stat
            stat_markups.append(hero_stat(
                s.get("value", ""),
                s.get("label", ""),
                s.get("desc", ""),
                t["text"],
                t["muted"],
                accent=accent,
            ))

        stats_str = ",\n    ".join(stat_markups)
        n_cols = len(stat_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(28pt)

  grid(
    columns: ({', '.join(['1fr'] * n_cols)}),
    gutter: 20pt,
    {stats_str}
  )

  v(1fr)
  {accent_bar(t['accent'], 'bottom')}
}}"""

    # -- Table slide -------------------------------------------------------

    def _table_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        headers = d.get("headers", [])
        rows = d.get("rows", [])
        footnote = d.get("footnote", "")

        table_markup = data_table(
            headers,
            rows,
            header_fill=t.get("accent", t.get("surface", "#1a3a5c")),
            header_text="#FFFFFF",
            bg=t["bg"],
            alt_bg=t.get("card_fill", t.get("surface", "#F5F5F5")),
            border=t["border"],
        )

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  {table_markup}

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Split slide -------------------------------------------------------

    def _split_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        left_title = d.get("left_title", "")
        left_items = d.get("left_items", [])
        right_title = d.get("right_title", "")
        right_items = d.get("right_items", [])

        left_bullets = "\n      ".join(f"- {_esc(item)}" for item in left_items)
        right_bullets = "\n      ".join(f"- {_esc(item)}" for item in right_items)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  grid(
    columns: (1fr, 1fr),
    gutter: 20pt,
    block(
      fill: {_rgb(t['card_fill'])},
      stroke: 0.75pt + {_rgb(t['border'])},
      radius: 3pt,
      inset: 14pt,
      width: 100%,
    )[
      #text(weight: "bold", size: 14pt, fill: {_rgb(t['text'])})[#upper("{_esc(left_title)}")]
      #v(8pt)
      #text(size: 11pt, fill: {_rgb(t['muted'])})[
        {left_bullets}
      ]
    ],
    block(
      fill: {_rgb(t['accent'])},
      radius: 3pt,
      inset: 14pt,
      width: 100%,
    )[
      #text(weight: "bold", size: 14pt, fill: {_rgb(t['title_fg'])})[#upper("{_esc(right_title)}")]
      #v(8pt)
      #text(size: 11pt, fill: {_rgb(t['title_fg'])})[
        {right_bullets}
      ]
    ],
  )

  {footer_bar('', t['border'], t['muted'])}
}}"""

    # -- Chart slide (image embed) -----------------------------------------

    def _chart_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        image_path = d.get("image_path", "")
        footnote = d.get("footnote", "")

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  align(center, image("{image_path}", width: 90%))

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Bar chart slide (native Typst) ------------------------------------

    def _bar_chart_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        bars = d.get("bars", [])  # [{"label": ..., "value": ..., "pct": ...}, ...]
        footnote = d.get("footnote", "")

        colors = t.get("chart_colors", ["#3fb950", "#58a6ff", "#f0883e", "#d2a8ff"])
        bar_markups = []
        for i, b in enumerate(bars):
            color = colors[i % len(colors)]
            bar_markups.append(bar_row(b["label"], b["value"], b["pct"], color, t["muted"]))

        bars_str = "\n  ".join(bar_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  {bars_str}

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- KPI strip slide ---------------------------------------------------

    def _kpi_strip_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        kpis = d.get("kpis", [])  # [{"value": ..., "label": ..., "highlight": bool}, ...]
        footnote = d.get("footnote", "")

        from inkline.typst.components import kpi_card
        kpi_markups = []
        for k in kpis:
            fill = t["accent"] if k.get("highlight") else t["card_fill"]
            text_color = t["title_fg"] if k.get("highlight") else t["text"]
            kpi_markups.append(kpi_card(k["value"], k["label"], fill, text_color))

        kpis_str = ",\n    ".join(kpi_markups)
        n_cols = len(kpi_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(20pt)

  grid(
    columns: ({', '.join(['1fr'] * n_cols)}),
    gutter: 8pt,
    {kpis_str}
  )

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Closing slide -----------------------------------------------------

    def _closing_slide(self, d: dict) -> str:
        t = self.t
        name = d.get("name", "")
        role = d.get("role", "")
        email = d.get("email", "")
        company = d.get("company", t.get("name", ""))
        tagline = d.get("tagline", "")

        return f"""#{{
  set page(fill: {_rgb(t['title_bg'])})
  set text(fill: {_rgb(t['title_fg'])})

  {accent_bar(t['accent'], 'top')}

  v(2cm)
  align(center)[
    #text(weight: "bold", size: 36pt, font: "{t.get('heading_font', 'Inter')}")[{_esc(company).upper()}]
    #v(0.5cm)
    #text(size: 16pt, fill: {_rgb(t['muted'])})[{_esc(tagline)}]
    #v(1.5cm)
    #text(weight: "bold", size: 18pt)[{_esc(name)}]
    #v(4pt)
    #text(size: 14pt, fill: {_rgb(t['muted'])})[{_esc(role)}]
    #v(4pt)
    #text(size: 14pt, fill: {_rgb(t['accent2'])})[{_esc(email)}]
  ]

  v(1fr)
  line(length: 100%, stroke: 0.5pt + {_rgb(t['muted'])})
  v(4pt)
  align(center, text(size: 9pt, fill: {_rgb(t['muted'])})[{_esc(t.get('confidentiality', ''))}])
}}"""


    # ==================================================================
    # INFOGRAPHIC SLIDE TYPES
    # ==================================================================

    # -- Timeline slide ----------------------------------------------------

    def _timeline_slide(self, d: dict) -> str:
        """Horizontal timeline with milestones.

        data: section, title, milestones [{date, label, desc?}], footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        milestones = d.get("milestones", [])
        footnote = d.get("footnote", "")

        n = len(milestones)
        if n == 0:
            return self._content_slide(d)

        # Build milestone nodes
        nodes = []
        for i, m in enumerate(milestones):
            date = _esc(m.get("date", ""))
            label = _esc(m.get("label", ""))
            desc = _esc(m.get("desc", ""))
            # Alternate above/below for visual rhythm
            is_above = i % 2 == 0
            node = f"""align(center)[
        #text(size: 8pt, weight: "bold", fill: {_rgb(t['accent'])})[{date}]
        #v(2pt)
        #block(
          fill: {_rgb(t['accent']) if i == n - 1 else _rgb(t['card_fill'])},
          stroke: 0.75pt + {_rgb(t['border'])},
          radius: 50%,
          width: 12pt,
          height: 12pt,
        )[]
        #v(2pt)
        #text(size: 9pt, weight: "bold", fill: {_rgb(t['text'])})[{label}]
        {f'#v(1pt)#text(size: 8pt, fill: {_rgb(t["muted"])})[{desc}]' if desc else ''}
      ]"""
            nodes.append(node)

        cols = ", ".join(["1fr"] * n)
        nodes_str = ",\n    ".join(nodes)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(1fr)

  // Timeline line
  place(center + horizon, line(length: 85%, stroke: 2pt + {_rgb(t['border'])}))

  // Milestone nodes
  grid(
    columns: ({cols}),
    gutter: 4pt,
    {nodes_str}
  )

  v(1fr)
  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Process flow slide ------------------------------------------------

    def _process_flow_slide(self, d: dict) -> str:
        """Numbered step sequence with arrows.

        data: section, title, steps [{number, title, desc}], footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        steps = d.get("steps", [])
        footnote = d.get("footnote", "")

        if not steps:
            return self._content_slide(d)

        # Build step blocks with arrows between them
        step_blocks = []
        for i, step in enumerate(steps):
            num = step.get("number", str(i + 1))
            step_title = _esc(step.get("title", ""))
            desc = _esc(step.get("desc", ""))

            block_str = f"""block(
        fill: {_rgb(t['card_fill'])},
        stroke: 0.75pt + {_rgb(t['border'])},
        radius: 4pt,
        inset: 10pt,
        width: 100%,
      )[
        #align(center)[
          #block(
            fill: {_rgb(t['accent'])},
            radius: 50%,
            width: 28pt,
            height: 28pt,
            inset: 4pt,
          )[#align(center + horizon, text(weight: "bold", size: 14pt, fill: {_rgb(t['title_fg'])})[{_esc(num)}])]
          #v(6pt)
          #text(weight: "bold", size: 11pt, fill: {_rgb(t['text'])})[#upper("{step_title}")]
          #v(3pt)
          #text(size: 9pt, fill: {_rgb(t['muted'])})[{desc}]
        ]
      ]"""
            step_blocks.append(block_str)

            # Add arrow between steps (not after last)
            if i < len(steps) - 1:
                step_blocks.append(
                    f'align(center + horizon, text(size: 20pt, fill: {_rgb(t["accent"])})[\\u{{2192}}])'
                )

        n_cols = len(steps) * 2 - 1  # steps + arrows
        cols = []
        for i in range(n_cols):
            cols.append("0.5fr" if i % 2 == 1 else "1fr")  # arrows get less space
        cols_str = ", ".join(cols)
        blocks_str = ",\n    ".join(step_blocks)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(1fr)

  grid(
    columns: ({cols_str}),
    gutter: 6pt,
    {blocks_str}
  )

  v(1fr)
  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Icon stat slide ---------------------------------------------------

    def _icon_stat_slide(self, d: dict) -> str:
        """Big number + emoji/icon + label — statistical infographic style.

        data: section, title, stats [{value, icon, label, desc?}], footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        stats = d.get("stats", [])
        footnote = d.get("footnote", "")

        if not stats:
            return self._content_slide(d)

        stat_blocks = []
        colors = t.get("chart_colors", [t["accent"], t.get("accent2", t["accent"])])
        for i, s in enumerate(stats):
            color = colors[i % len(colors)]
            value = _esc(s.get("value", ""))
            icon = s.get("icon", "")  # emoji or unicode character
            label = _esc(s.get("label", ""))
            desc = _esc(s.get("desc", ""))

            stat_blocks.append(f"""block(
        fill: {_rgb(t['card_fill'])},
        stroke: 0.75pt + {_rgb(t['border'])},
        radius: 4pt,
        inset: 14pt,
        width: 100%,
      )[
        #align(center)[
          {f'#text(size: 28pt)[{icon}]#v(4pt)' if icon else ''}
          #text(weight: "bold", size: 36pt, fill: {_rgb(color)})[{value}]
          #v(4pt)
          #text(weight: "bold", size: 10pt, fill: {_rgb(t['muted'])})[#upper("{label}")]
          {f'#v(2pt)#text(size: 9pt, fill: {_rgb(t["muted"])})[{desc}]' if desc else ''}
        ]
      ]""")

        n = len(stat_blocks)
        cols_str = ", ".join(["1fr"] * n)
        blocks_str = ",\n    ".join(stat_blocks)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(1fr)

  grid(
    columns: ({cols_str}),
    gutter: 14pt,
    {blocks_str}
  )

  v(1fr)
  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Progress bars slide -----------------------------------------------

    def _progress_bars_slide(self, d: dict) -> str:
        """Labelled percentage bars — skill bars, completion, ratings.

        data: section, title, bars [{label, pct, value?}], footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        bars = d.get("bars", [])
        footnote = d.get("footnote", "")

        if not bars:
            return self._content_slide(d)

        colors = t.get("chart_colors", [t["accent"]])
        bar_rows = []
        for i, b in enumerate(bars):
            label = _esc(b.get("label", ""))
            pct = b.get("pct", 0)
            value = _esc(b.get("value", f"{pct}%"))
            color = colors[i % len(colors)]

            bar_rows.append(f"""  grid(
    columns: (4cm, 1fr, 1.5cm),
    gutter: 8pt,
    align(right + horizon, text(size: 10pt, weight: "bold", fill: {_rgb(t['text'])})[{label}]),
    block(width: 100%, height: 20pt, fill: {_rgb(t['card_fill'])}, stroke: 0.5pt + {_rgb(t['border'])}, radius: 3pt)[
      #block(width: {pct}%, height: 100%, fill: {_rgb(color)}, radius: 3pt)[]
    ],
    align(left + horizon, text(size: 10pt, weight: "bold", fill: {_rgb(t['accent'])})[{value}]),
  )""")

        bars_str = "\n  v(8pt)\n  ".join(bar_rows)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(20pt)

  {bars_str}

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Pyramid slide -----------------------------------------------------

    def _pyramid_slide(self, d: dict) -> str:
        """3-5 tier hierarchy pyramid.

        data: section, title, tiers [{label, desc?}] (top to bottom), footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        tiers = d.get("tiers", [])
        footnote = d.get("footnote", "")

        if not tiers:
            return self._content_slide(d)

        colors = t.get("chart_colors", [t["accent"]])
        n = len(tiers)
        tier_blocks = []
        for i, tier in enumerate(tiers):
            label = _esc(tier.get("label", ""))
            desc = _esc(tier.get("desc", ""))
            color = colors[i % len(colors)]
            # Each tier gets wider — top is narrowest
            width_pct = 30 + (i * (70 // n))

            tier_blocks.append(f"""  align(center, block(
    fill: {_rgb(color)},
    radius: 3pt,
    inset: (x: 12pt, y: 6pt),
    width: {width_pct}%,
  )[
    #align(center)[
      #text(weight: "bold", size: 11pt, fill: white)[#upper("{label}")]
      {f'#v(2pt)#text(size: 9pt, fill: white.transparentize(30%))[{desc}]' if desc else ''}
    ]
  ])""")

        tiers_str = "\n  v(4pt)\n".join(tier_blocks)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(1fr)

{tiers_str}

  v(1fr)
  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Comparison slide --------------------------------------------------

    def _comparison_slide(self, d: dict) -> str:
        """Structured side-by-side comparison with metrics.

        data: section, title, left {name, items [{label, value}]},
              right {name, items [{label, value}]}, footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        left = d.get("left", {})
        right = d.get("right", {})
        footnote = d.get("footnote", "")

        left_name = _esc(left.get("name", "Option A"))
        right_name = _esc(right.get("name", "Option B"))
        left_items = left.get("items", [])
        right_items = right.get("items", [])

        # Build comparison rows
        rows = []
        max_rows = max(len(left_items), len(right_items))
        for i in range(max_rows):
            l_item = left_items[i] if i < len(left_items) else {}
            r_item = right_items[i] if i < len(right_items) else {}
            l_label = _esc(l_item.get("label", "") if isinstance(l_item, dict) else str(l_item))
            l_value = _esc(l_item.get("value", "") if isinstance(l_item, dict) else "")
            r_label = _esc(r_item.get("label", "") if isinstance(r_item, dict) else str(r_item))
            r_value = _esc(r_item.get("value", "") if isinstance(r_item, dict) else "")

            fill = _rgb(t['card_fill']) if i % 2 == 0 else _rgb(t['bg'])
            rows.append(f"""    grid(
      columns: (1fr, 1fr),
      gutter: 14pt,
      block(fill: {fill}, inset: 8pt, width: 100%, radius: 2pt)[
        #text(size: 10pt, fill: {_rgb(t['muted'])})[{l_label}]
        {f'#h(1fr)#text(size: 10pt, weight: "bold", fill: {_rgb(t["text"])})[{l_value}]' if l_value else ''}
      ],
      block(fill: {fill}, inset: 8pt, width: 100%, radius: 2pt)[
        #text(size: 10pt, fill: {_rgb(t['muted'])})[{r_label}]
        {f'#h(1fr)#text(size: 10pt, weight: "bold", fill: {_rgb(t["text"])})[{r_value}]' if r_value else ''}
      ],
    )""")

        rows_str = "\n    v(2pt)\n".join(rows)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  // Column headers
  grid(
    columns: (1fr, 1fr),
    gutter: 14pt,
    block(fill: {_rgb(t['card_fill'])}, stroke: (bottom: 2pt + {_rgb(t['accent'])}), inset: 10pt, width: 100%)[
      #align(center, text(weight: "bold", size: 14pt, fill: {_rgb(t['accent'])})[#upper("{left_name}")])
    ],
    block(fill: {_rgb(t['accent'])}, inset: 10pt, width: 100%, radius: (top: 3pt))[
      #align(center, text(weight: "bold", size: 14pt, fill: {_rgb(t['title_fg'])})[#upper("{right_name}")])
    ],
  )
  v(6pt)

  // Comparison rows
  {rows_str}

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""


def _esc(text: str) -> str:
    """Escape special Typst characters."""
    if not text:
        return ""
    return (
        text
        .replace("\\", "\\\\")
        .replace("#", "\\#")
        .replace("$", "\\$")
        .replace("@", "\\@")
        .replace("<", "\\<")
        .replace(">", "\\>")
    )
