"""Typst slide renderer — generates 16:9 presentation markup from structured data.

Produces a complete ``.typ`` source string that compiles to a multi-page PDF
where each page is one slide.

Slide types: title, content, three_card, four_card, stat, table, split,
chart, closing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from inkline.typst.components import (
    _rgb,
    accent_bar,
    bar_row,
    card,
    card_title,
    data_table,
    footer_bar,
    hero_stat,
    section_badge,
    slide_title,
)


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class SlideSpec:
    """Specification for a single slide."""
    slide_type: str  # title, content, three_card, four_card, stat, table, split, chart, closing
    data: dict[str, Any] = field(default_factory=dict)


@dataclass
class DeckSpec:
    """Specification for a full slide deck."""
    slides: list[SlideSpec] = field(default_factory=list)
    title: str = "Untitled"
    date: str = ""
    subtitle: str = ""


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------

class TypstSlideRenderer:
    """Renders SlideSpec objects into Typst markup."""

    def __init__(self, theme: dict):
        self.t = theme

    def render_deck(self, spec: DeckSpec) -> str:
        """Render a full deck to Typst source."""
        parts = [self._preamble()]
        for i, slide in enumerate(spec.slides):
            if i > 0:
                parts.append("#pagebreak()")
            parts.append(self._render_slide(slide))
        return "\n\n".join(parts)

    # -- Preamble ----------------------------------------------------------

    def _preamble(self) -> str:
        t = self.t
        heading_font = t.get("heading_font", "Inter")
        body_font = t.get("body_font", "Inter")
        body_size = t.get("body_size", 11)
        return f"""// Generated by Inkline - Typst Slide Engine
#set page(width: 25.4cm, height: 14.29cm, margin: (x: 1.2cm, y: 0.8cm))
#set text(font: "{body_font}", size: {body_size}pt)
#set par(leading: 0.7em)"""

    # -- Slide dispatch ----------------------------------------------------

    def _render_slide(self, slide: SlideSpec) -> str:
        renderer = {
            "title": self._title_slide,
            "content": self._content_slide,
            "three_card": self._three_card_slide,
            "four_card": self._four_card_slide,
            "stat": self._stat_slide,
            "table": self._table_slide,
            "split": self._split_slide,
            "chart": self._chart_slide,
            "closing": self._closing_slide,
            "bar_chart": self._bar_chart_slide,
            "kpi_strip": self._kpi_strip_slide,
        }.get(slide.slide_type)
        if not renderer:
            return f'// Unknown slide type: {slide.slide_type}'
        return renderer(slide.data)

    # -- Title slide -------------------------------------------------------

    def _title_slide(self, d: dict) -> str:
        t = self.t
        company = d.get("company", t.get("name", ""))
        tagline = d.get("tagline", "")
        date = d.get("date", "")
        subtitle = d.get("subtitle", "")
        desc = t.get("desc", "")
        conf = t.get("confidentiality", "")

        return f"""#{{
  set page(fill: {_rgb(t['title_bg'])})
  set text(fill: {_rgb(t['title_fg'])})

  {accent_bar(t['accent'], 'top')}

  v(1.5cm)
  text(size: 9pt, fill: {_rgb(t['muted'])})[#upper("{_esc(desc)}")]
  v(0.5cm)
  text(weight: "bold", size: 52pt, font: "{t.get('heading_font', 'Inter')}")[{_esc(company).upper()}]
  v(0.5cm)
  text(weight: "bold", size: 24pt, font: "{t.get('heading_font', 'Inter')}")[{_esc(tagline)}]
  {f'v(0.3cm){chr(10)}  text(size: 14pt, fill: {_rgb(t["muted"])})[{_esc(subtitle)}]' if subtitle else ''}
  v(1fr)
  line(length: 100%, stroke: 0.5pt + {_rgb(t['muted'])})
  v(4pt)
  grid(
    columns: (1fr, 1fr),
    text(weight: "bold", size: 11pt)[{_esc(d.get('left_footer', ''))}],
    align(right, text(size: 9pt, fill: {_rgb(t['muted'])})[{_esc(conf)} {_esc(date)}]),
  )
}}"""

    # -- Content slide -----------------------------------------------------

    def _content_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        items = d.get("items", [])
        footnote = d.get("footnote", "")

        bullets = "\n    ".join(f"- {_esc(item)}" for item in items)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  text(size: 12pt, fill: {_rgb(t['text'])})[
    {bullets}
  ]

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Three card slide --------------------------------------------------

    def _three_card_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        cards = d.get("cards", [])
        footnote = d.get("footnote", "")
        highlight_idx = d.get("highlight_index", 1)  # Which card gets accent fill

        card_markups = []
        for i, c in enumerate(cards[:3]):
            if i == highlight_idx:
                # Accent card
                cm = card(
                    f'{card_title(c.get("title", ""), t["title_fg"])}\n      #v(6pt)\n      #text(size: 10.5pt, fill: {_rgb(t["title_fg"])})[{_esc(c.get("body", ""))}]',
                    fill=t["accent"],
                    text_color=t["title_fg"],
                )
            else:
                cm = card(
                    f'{card_title(c.get("title", ""), t["text"])}\n      #v(6pt)\n      #text(size: 10.5pt, fill: {_rgb(t["muted"])})[{_esc(c.get("body", ""))}]',
                    fill=t["card_fill"],
                    border=t["border"],
                    text_color=t["text"],
                )
            card_markups.append(cm)

        cards_str = ",\n    ".join(card_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  grid(
    columns: (1fr, 1fr, 1fr),
    gutter: 14pt,
    {cards_str}
  )

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Four card slide ---------------------------------------------------

    def _four_card_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        cards = d.get("cards", [])
        footnote = d.get("footnote", "")

        card_markups = []
        for c in cards[:4]:
            cm = card(
                f'{card_title(c.get("title", ""), t["text"])}\n      #v(6pt)\n      #text(size: 10.5pt, fill: {_rgb(t["muted"])})[{_esc(c.get("body", ""))}]',
                fill=t["card_fill"],
                border=t["border"],
                text_color=t["text"],
            )
            card_markups.append(cm)

        cards_str = ",\n    ".join(card_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  grid(
    columns: (1fr, 1fr),
    gutter: 14pt,
    {cards_str}
  )

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Stat slide --------------------------------------------------------

    def _stat_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        stats = d.get("stats", [])

        stat_markups = []
        for i, s in enumerate(stats[:4]):
            accent = t["accent"] if i == 1 else None  # Highlight second stat
            stat_markups.append(hero_stat(
                s.get("value", ""),
                s.get("label", ""),
                s.get("desc", ""),
                t["text"],
                t["muted"],
                accent=accent,
            ))

        stats_str = ",\n    ".join(stat_markups)
        n_cols = len(stat_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(28pt)

  grid(
    columns: ({', '.join(['1fr'] * n_cols)}),
    gutter: 20pt,
    {stats_str}
  )

  v(1fr)
  {accent_bar(t['accent'], 'bottom')}
}}"""

    # -- Table slide -------------------------------------------------------

    def _table_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        headers = d.get("headers", [])
        rows = d.get("rows", [])
        footnote = d.get("footnote", "")

        table_markup = data_table(
            headers,
            rows,
            header_fill=t.get("accent", t.get("surface", "#1a3a5c")),
            header_text="#FFFFFF",
            bg=t["bg"],
            alt_bg=t.get("card_fill", t.get("surface", "#F5F5F5")),
            border=t["border"],
        )

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  {table_markup}

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Split slide -------------------------------------------------------

    def _split_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        left_title = d.get("left_title", "")
        left_items = d.get("left_items", [])
        right_title = d.get("right_title", "")
        right_items = d.get("right_items", [])

        left_bullets = "\n      ".join(f"- {_esc(item)}" for item in left_items)
        right_bullets = "\n      ".join(f"- {_esc(item)}" for item in right_items)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  grid(
    columns: (1fr, 1fr),
    gutter: 20pt,
    block(
      fill: {_rgb(t['card_fill'])},
      stroke: 0.75pt + {_rgb(t['border'])},
      radius: 3pt,
      inset: 14pt,
      width: 100%,
    )[
      #text(weight: "bold", size: 14pt, fill: {_rgb(t['text'])})[#upper("{_esc(left_title)}")]
      #v(8pt)
      #text(size: 11pt, fill: {_rgb(t['muted'])})[
        {left_bullets}
      ]
    ],
    block(
      fill: {_rgb(t['accent'])},
      radius: 3pt,
      inset: 14pt,
      width: 100%,
    )[
      #text(weight: "bold", size: 14pt, fill: {_rgb(t['title_fg'])})[#upper("{_esc(right_title)}")]
      #v(8pt)
      #text(size: 11pt, fill: {_rgb(t['title_fg'])})[
        {right_bullets}
      ]
    ],
  )

  {footer_bar('', t['border'], t['muted'])}
}}"""

    # -- Chart slide (image embed) -----------------------------------------

    def _chart_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        image_path = d.get("image_path", "")
        footnote = d.get("footnote", "")

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  align(center, image("{image_path}", width: 90%))

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Bar chart slide (native Typst) ------------------------------------

    def _bar_chart_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        bars = d.get("bars", [])  # [{"label": ..., "value": ..., "pct": ...}, ...]
        footnote = d.get("footnote", "")

        colors = t.get("chart_colors", ["#3fb950", "#58a6ff", "#f0883e", "#d2a8ff"])
        bar_markups = []
        for i, b in enumerate(bars):
            color = colors[i % len(colors)]
            bar_markups.append(bar_row(b["label"], b["value"], b["pct"], color, t["muted"]))

        bars_str = "\n  ".join(bar_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  {bars_str}

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- KPI strip slide ---------------------------------------------------

    def _kpi_strip_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        kpis = d.get("kpis", [])  # [{"value": ..., "label": ..., "highlight": bool}, ...]
        footnote = d.get("footnote", "")

        from inkline.typst.components import kpi_card
        kpi_markups = []
        for k in kpis:
            fill = t["accent"] if k.get("highlight") else t["card_fill"]
            text_color = t["title_fg"] if k.get("highlight") else t["text"]
            kpi_markups.append(kpi_card(k["value"], k["label"], fill, text_color))

        kpis_str = ",\n    ".join(kpi_markups)
        n_cols = len(kpi_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(20pt)

  grid(
    columns: ({', '.join(['1fr'] * n_cols)}),
    gutter: 8pt,
    {kpis_str}
  )

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Closing slide -----------------------------------------------------

    def _closing_slide(self, d: dict) -> str:
        t = self.t
        name = d.get("name", "")
        role = d.get("role", "")
        email = d.get("email", "")
        company = d.get("company", t.get("name", ""))
        tagline = d.get("tagline", "")

        return f"""#{{
  set page(fill: {_rgb(t['title_bg'])})
  set text(fill: {_rgb(t['title_fg'])})

  {accent_bar(t['accent'], 'top')}

  v(2cm)
  align(center)[
    #text(weight: "bold", size: 36pt, font: "{t.get('heading_font', 'Inter')}")[{_esc(company).upper()}]
    #v(0.5cm)
    #text(size: 16pt, fill: {_rgb(t['muted'])})[{_esc(tagline)}]
    #v(1.5cm)
    #text(weight: "bold", size: 18pt)[{_esc(name)}]
    #v(4pt)
    #text(size: 14pt, fill: {_rgb(t['muted'])})[{_esc(role)}]
    #v(4pt)
    #text(size: 14pt, fill: {_rgb(t['accent2'])})[{_esc(email)}]
  ]

  v(1fr)
  line(length: 100%, stroke: 0.5pt + {_rgb(t['muted'])})
  v(4pt)
  align(center, text(size: 9pt, fill: {_rgb(t['muted'])})[{_esc(t.get('confidentiality', ''))}])
}}"""


def _esc(text: str) -> str:
    """Escape special Typst characters."""
    if not text:
        return ""
    return (
        text
        .replace("\\", "\\\\")
        .replace("#", "\\#")
        .replace("$", "\\$")
        .replace("@", "\\@")
        .replace("<", "\\<")
        .replace(">", "\\>")
    )
