"""Typst slide renderer — generates 16:9 presentation markup from structured data.

Produces a complete ``.typ`` source string that compiles to a multi-page PDF
where each page is one slide.

Slide types: title, content, three_card, four_card, stat, table, split,
chart, closing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from inkline.typst.components import (
    _rgb,
    accent_bar,
    bar_row,
    card,
    card_title,
    data_table,
    footer_bar,
    hero_stat,
    section_badge,
    slide_title,
)


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class SlideSpec:
    """Specification for a single slide."""
    slide_type: str  # title, content, three_card, four_card, stat, table, split, chart, closing
    data: dict[str, Any] = field(default_factory=dict)


@dataclass
class DeckSpec:
    """Specification for a full slide deck."""
    slides: list[SlideSpec] = field(default_factory=list)
    title: str = "Untitled"
    date: str = ""
    subtitle: str = ""


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------

class TypstSlideRenderer:
    """Renders SlideSpec objects into Typst markup."""

    # Slide geometry (16:9 at 25.4cm × 14.29cm with 1.2cm x-margin, 0.8cm y-margin)
    SLIDE_WIDTH_CM = 23.0   # usable content width (25.4 - 2×1.2)
    SLIDE_HEIGHT_CM = 12.69  # usable content height (14.29 - 2×0.8)
    # After section badge + title + spacing: ~2.5cm header, ~1.5cm footer
    BODY_HEIGHT_CM = 8.5    # usable body area for content
    # Content limits per slide type
    MAX_BULLETS = 8
    MAX_TABLE_ROWS = 12
    MAX_BARS = 8
    MAX_TIMELINE_NODES = 8
    MAX_PROCESS_STEPS = 5
    MAX_PROGRESS_BARS = 6
    MAX_PYRAMID_TIERS = 6
    MAX_COMPARISON_ROWS = 8

    def __init__(self, theme: dict):
        self.t = theme

    # Slide types that use #page(...)[content] (function form) which
    # starts its own page — no #pagebreak() needed before them.
    _SELF_PAGED_TYPES = {"title", "closing"}

    def render_deck(self, spec: DeckSpec) -> str:
        """Render a full deck to Typst source."""
        parts = [self._preamble()]
        for i, slide in enumerate(spec.slides):
            # #pagebreak() between slides — but skip when the next slide
            # uses #page(...) which starts its own page. Otherwise we get
            # an empty page between them.
            if i > 0 and slide.slide_type not in self._SELF_PAGED_TYPES:
                parts.append("#pagebreak()")
            parts.append(self._render_slide(slide))
        return "\n\n".join(parts)

    # -- Preamble ----------------------------------------------------------

    def _preamble(self) -> str:
        t = self.t
        heading_font = t.get("heading_font", "Inter")
        body_font = t.get("body_font", "Inter")
        body_size = t.get("body_size", 11)
        accent = t.get("accent", "#6366F1")
        muted = t.get("muted", "#64748B")
        bg = t.get("bg", "#FFFFFF")
        brand_name = t.get("name", "")
        # Footer tagline — prefer brand footer_text, fall back to brand tagline,
        # NEVER use template desc (that's metadata for humans, not slide chrome)
        footer_tagline = t.get("footer_text") or t.get("tagline") or ""
        return f"""// Generated by Inkline - Typst Slide Engine
#set page(
  width: 25.4cm,
  height: 14.29cm,
  margin: (top: 1.4cm, bottom: 1.2cm, left: 1.4cm, right: 1.4cm),
  fill: {_rgb(bg)},
  header: context {{
    if counter(page).get().first() > 1 {{
      grid(
        columns: (auto, 1fr, auto),
        align: horizon,
        block(width: 2.4cm, height: 3pt, fill: {_rgb(accent)}),
        h(1fr),
        text(size: 8pt, weight: "bold", tracking: 1pt, fill: {_rgb(muted)})[{_esc(brand_name).upper()}],
      )
    }}
  }},
  footer: context {{
    if counter(page).get().first() > 1 {{
      grid(
        columns: (auto, 1fr, auto),
        align: horizon,
        text(size: 8pt, fill: {_rgb(muted)})[{_esc(footer_tagline)}],
        h(1fr),
        text(size: 8pt, weight: "bold", fill: {_rgb(accent)})[#counter(page).display() / #context counter(page).final().first()],
      )
    }}
  }},
)
#set text(font: "{body_font}", size: {body_size}pt, fill: {_rgb(t.get('text', '#0F172A'))})
#set par(leading: 0.7em)"""

    # -- Slide dispatch ----------------------------------------------------

    def _render_slide(self, slide: SlideSpec) -> str:
        renderer = {
            "title": self._title_slide,
            "content": self._content_slide,
            "three_card": self._three_card_slide,
            "four_card": self._four_card_slide,
            "stat": self._stat_slide,
            "table": self._table_slide,
            "split": self._split_slide,
            "chart": self._chart_slide,
            "closing": self._closing_slide,
            "bar_chart": self._bar_chart_slide,
            "kpi_strip": self._kpi_strip_slide,
            "timeline": self._timeline_slide,
            "process_flow": self._process_flow_slide,
            "icon_stat": self._icon_stat_slide,
            "progress_bars": self._progress_bars_slide,
            "pyramid": self._pyramid_slide,
            "comparison": self._comparison_slide,
            "feature_grid": self._feature_grid_slide,
            "dashboard": self._dashboard_slide,
            "chart_caption": self._chart_caption_slide,
        }.get(slide.slide_type)
        if not renderer:
            return f'// Unknown slide type: {slide.slide_type}'
        return renderer(slide.data)

    # -- Title slide -------------------------------------------------------

    def _title_slide(self, d: dict) -> str:
        t = self.t
        company = d.get("company", t.get("name", ""))
        tagline = d.get("tagline", "")
        date = d.get("date", "")
        subtitle = d.get("subtitle", "")
        left_footer = d.get("left_footer", "")
        heading_font = t.get("heading_font", "Inter")

        # Resolve title bg/fg — if brand bg is light, use it for title too
        # (matches advisor pitch style: cream bg, black text, logo visible)
        title_bg = t.get("title_bg", t.get("bg", "#1B283B"))
        title_fg = t.get("title_fg", "#FFFFFF")
        # Logo path for title slide
        logo_path = t.get("logo_light_path", "")

        # Title slide layout matches advisor pitch:
        # - Large shield left-aligned, vertically centred with company name
        # - Company name in huge bold uppercase to the right of shield
        # - Tagline below in bold uppercase
        # - Horizontal line, then subtitle text
        # - Footer with date + confidentiality
        return f"""#page(
  fill: {_rgb(title_bg)},
  margin: (top: 1.4cm, bottom: 1.2cm, left: 1.6cm, right: 1.6cm),
  header: none,
  footer: none,
)[
  #set text(fill: {_rgb(title_fg)})

  #v(1fr)

  // Shield + company name — shield is large, left-aligned, name to the right
  #grid(
    columns: (4.5cm, 1fr),
    gutter: 16pt,
    align: horizon,
    {f'image("{logo_path}", height: 4cm),' if logo_path else 'none,'}
    text(weight: "bold", size: 80pt, font: "{heading_font}", tracking: -2pt)[#upper("{_esc(company)}")]
  )

  #v(0.6cm)

  // Tagline — large bold uppercase, full width
  #text(weight: "bold", size: 20pt, font: "{heading_font}", fill: {_rgb(title_fg)})[#upper("{_esc(tagline)}")]

  #v(0.5cm)
  #line(length: 100%, stroke: 0.5pt + {_rgb(t['muted'])})
  #v(0.4cm)
  {f'#text(size: 11pt, fill: {_rgb(t["muted"])})[{_esc(subtitle)}]#v(4pt)' if subtitle else ''}
  {f'#text(weight: "bold", size: 11pt, fill: {_rgb(title_fg)})[{_esc(left_footer)}]#v(4pt)' if left_footer else ''}

  #v(1fr)

  // Footer — date + confidentiality
  #grid(
    columns: (1fr, auto),
    align: bottom,
    text(size: 9pt, fill: {_rgb(t['muted'])})[{_esc(date)}],
    text(size: 8pt, weight: "bold", tracking: 1pt, fill: {_rgb(t['muted'])})[{_esc(t.get('confidentiality', ''))}],
  )
]"""

    # -- Content slide -----------------------------------------------------

    def _content_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        items = d.get("items", [])[:self.MAX_BULLETS]
        footnote = d.get("footnote", "")

        bullets = "\n    ".join(f"- {_esc(item)}" for item in items)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  text(size: 12pt, fill: {_rgb(t['text'])})[
    {bullets}
  ]

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Three card slide --------------------------------------------------

    def _three_card_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        cards = d.get("cards", [])
        footnote = d.get("footnote", "")
        highlight_idx = d.get("highlight_index", 1)  # Which card gets accent fill

        card_markups = []
        for i, c in enumerate(cards[:3]):
            if i == highlight_idx:
                # Accent card
                cm = card(
                    f'{card_title(c.get("title", ""), t["title_fg"])}\n      #v(6pt)\n      #text(size: 10.5pt, fill: {_rgb(t["title_fg"])})[{_esc(c.get("body", ""))}]',
                    fill=t["accent"],
                    text_color=t["title_fg"],
                )
            else:
                cm = card(
                    f'{card_title(c.get("title", ""), t["text"])}\n      #v(6pt)\n      #text(size: 10.5pt, fill: {_rgb(t["muted"])})[{_esc(c.get("body", ""))}]',
                    fill=t["card_fill"],
                    border=t["border"],
                    text_color=t["text"],
                )
            card_markups.append(cm)

        cards_str = ",\n    ".join(card_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}

  v(1fr)

  grid(
    columns: (1fr, 1fr, 1fr),
    gutter: 14pt,
    {cards_str}
  )

  v(1fr)

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Four card slide ---------------------------------------------------

    def _four_card_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        cards = d.get("cards", [])
        footnote = d.get("footnote", "")

        card_markups = []
        for c in cards[:4]:
            cm = card(
                f'{card_title(c.get("title", ""), t["text"])}\n      #v(6pt)\n      #text(size: 10.5pt, fill: {_rgb(t["muted"])})[{_esc(c.get("body", ""))}]',
                fill=t["card_fill"],
                border=t["border"],
                text_color=t["text"],
            )
            card_markups.append(cm)

        cards_str = ",\n    ".join(card_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}

  v(1fr)

  grid(
    columns: (1fr, 1fr),
    gutter: 14pt,
    {cards_str}
  )

  v(1fr)

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Stat slide --------------------------------------------------------

    def _stat_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        stats = d.get("stats", [])

        stat_markups = []
        for i, s in enumerate(stats[:4]):
            accent = t["accent"] if i == 1 else None  # Highlight second stat
            stat_markups.append(hero_stat(
                s.get("value", ""),
                s.get("label", ""),
                s.get("desc", ""),
                t["text"],
                t["muted"],
                accent=accent,
            ))

        stats_str = ",\n    ".join(stat_markups)
        n_cols = len(stat_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(28pt)

  grid(
    columns: ({', '.join(['1fr'] * n_cols)}),
    gutter: 20pt,
    {stats_str}
  )

  v(1fr)
  {accent_bar(t['accent'], 'bottom')}
}}"""

    # -- Table slide -------------------------------------------------------

    def _table_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        headers = d.get("headers", [])
        rows = d.get("rows", [])[:self.MAX_TABLE_ROWS]
        footnote = d.get("footnote", "")

        table_markup = data_table(
            headers,
            rows,
            header_fill=t.get("accent", t.get("surface", "#1a3a5c")),
            header_text="#FFFFFF",
            bg=t["bg"],
            alt_bg=t.get("card_fill", t.get("surface", "#F5F5F5")),
            border=t["border"],
        )

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  {table_markup}

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Split slide -------------------------------------------------------

    def _split_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        left_title = d.get("left_title", "")
        left_items = d.get("left_items", [])
        right_title = d.get("right_title", "")
        right_items = d.get("right_items", [])

        left_bullets = "\n      ".join(f"- {_esc(item)}" for item in left_items[:self.MAX_BULLETS])
        right_bullets = "\n      ".join(f"- {_esc(item)}" for item in right_items[:self.MAX_BULLETS])

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  grid(
    columns: (1fr, 1fr),
    gutter: 20pt,
    block(
      fill: {_rgb(t['card_fill'])},
      stroke: 0.75pt + {_rgb(t['border'])},
      radius: 3pt,
      inset: 14pt,
      width: 100%,
    )[
      #text(weight: "bold", size: 14pt, fill: {_rgb(t['text'])})[#upper("{_esc(left_title)}")]
      #v(8pt)
      #text(size: 11pt, fill: {_rgb(t['muted'])})[
        {left_bullets}
      ]
    ],
    block(
      fill: {_rgb(t['accent'])},
      radius: 3pt,
      inset: 14pt,
      width: 100%,
    )[
      #text(weight: "bold", size: 14pt, fill: {_rgb(t['title_fg'])})[#upper("{_esc(right_title)}")]
      #v(8pt)
      #text(size: 11pt, fill: {_rgb(t['title_fg'])})[
        {right_bullets}
      ]
    ],
  )

  {footer_bar('', t['border'], t['muted'])}
}}"""

    # -- Chart slide (image embed) -----------------------------------------

    def _chart_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        image_path = d.get("image_path", "")
        footnote = d.get("footnote", "")

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  align(center, image("{image_path}", width: 90%, height: 8.5cm))

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Bar chart slide (native Typst) ------------------------------------

    def _bar_chart_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        bars = d.get("bars", [])[:self.MAX_BARS]
        footnote = d.get("footnote", "")

        colors = t.get("chart_colors", ["#3fb950", "#58a6ff", "#f0883e", "#d2a8ff"])
        bar_markups = []
        for i, b in enumerate(bars):
            color = colors[i % len(colors)]
            bar_markups.append(bar_row(b["label"], b["value"], b["pct"], color, t["muted"]))

        bars_str = "\n  ".join(bar_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  {bars_str}

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- KPI strip slide ---------------------------------------------------

    def _kpi_strip_slide(self, d: dict) -> str:
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        kpis = d.get("kpis", [])  # [{"value": ..., "label": ..., "highlight": bool}, ...]
        footnote = d.get("footnote", "")

        from inkline.typst.components import kpi_card
        kpi_markups = []
        for k in kpis:
            fill = t["accent"] if k.get("highlight") else t["card_fill"]
            text_color = t["title_fg"] if k.get("highlight") else t["text"]
            kpi_markups.append(kpi_card(k["value"], k["label"], fill, text_color))

        kpis_str = ",\n    ".join(kpi_markups)
        n_cols = len(kpi_markups)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(20pt)

  grid(
    columns: ({', '.join(['1fr'] * n_cols)}),
    gutter: 8pt,
    {kpis_str}
  )

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Closing slide -----------------------------------------------------

    def _closing_slide(self, d: dict) -> str:
        t = self.t
        name = d.get("name", "")
        role = d.get("role", "")
        email = d.get("email", "")
        company = d.get("company", t.get("name", ""))
        tagline = d.get("tagline", "")
        heading_font = t.get("heading_font", "Inter")

        # Self-contained #page() — no set rule leak
        logo_path = t.get("logo_light_path", "")

        return f"""#page(
  fill: {_rgb(t['title_bg'])},
  margin: (top: 1.4cm, bottom: 1.2cm, left: 1.6cm, right: 1.6cm),
  header: none,
  footer: none,
)[
  #set text(fill: {_rgb(t['title_fg'])})

  #v(1fr)
  #align(center)[
    {f'#image("{logo_path}", width: 1.5cm)#v(0.2cm)' if logo_path else ''}
    #text(weight: "bold", size: 44pt, font: "{heading_font}", tracking: -1pt)[#upper("{_esc(company)}")]
    #v(0.2cm)
    #text(size: 12pt, fill: {_rgb(t['muted'])})[{_esc(tagline)}]
    #v(0.6cm)
    #block(fill: {_rgb(t['accent'])}, inset: (x: 14pt, y: 6pt), radius: 4pt)[
      #text(weight: "bold", size: 14pt, fill: white)[{_esc(name)}]
    ]
    #v(0.3cm)
    #text(size: 10pt, fill: {_rgb(t['muted'])})[{_esc(role)}]
    #v(2pt)
    #text(size: 10pt, weight: "bold", fill: {_rgb(t['accent2'])})[{_esc(email)}]
  ]

  #v(1fr)

  // Bottom — confidentiality
  #align(center)[
    #text(size: 8pt, weight: "bold", tracking: 1pt, fill: {_rgb(t['muted'])})[{_esc(t.get('confidentiality', ''))}]
  ]
]"""


    # ==================================================================
    # INFOGRAPHIC SLIDE TYPES
    # ==================================================================

    # -- Timeline slide ----------------------------------------------------

    def _timeline_slide(self, d: dict) -> str:
        """Horizontal timeline with milestones.

        data: section, title, milestones [{date, label, desc?}], footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        milestones = d.get("milestones", [])[:self.MAX_TIMELINE_NODES]
        footnote = d.get("footnote", "")

        n = len(milestones)
        if n == 0:
            return self._content_slide(d)

        # Build milestone nodes
        nodes = []
        for i, m in enumerate(milestones):
            date = _esc(m.get("date", ""))
            label = _esc(m.get("label", ""))
            desc = _esc(m.get("desc", ""))
            # Alternate above/below for visual rhythm
            is_above = i % 2 == 0
            node = f"""align(center)[
        #text(size: 8pt, weight: "bold", fill: {_rgb(t['accent'])})[{date}]
        #v(2pt)
        #block(
          fill: {_rgb(t['accent']) if i == n - 1 else _rgb(t['card_fill'])},
          stroke: 0.75pt + {_rgb(t['border'])},
          radius: 50%,
          width: 12pt,
          height: 12pt,
        )[]
        #v(2pt)
        #text(size: 9pt, weight: "bold", fill: {_rgb(t['text'])})[{label}]
        {f'#v(1pt)#text(size: 8pt, fill: {_rgb(t["muted"])})[{desc}]' if desc else ''}
      ]"""
            nodes.append(node)

        cols = ", ".join(["1fr"] * n)
        nodes_str = ",\n    ".join(nodes)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(1fr)

  // Timeline line
  place(center + horizon, line(length: 85%, stroke: 2pt + {_rgb(t['border'])}))

  // Milestone nodes
  grid(
    columns: ({cols}),
    gutter: 4pt,
    {nodes_str}
  )

  v(1fr)
  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Process flow slide ------------------------------------------------

    def _process_flow_slide(self, d: dict) -> str:
        """Numbered step sequence with arrows.

        data: section, title, steps [{number, title, desc}], footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        steps = d.get("steps", [])[:self.MAX_PROCESS_STEPS]
        footnote = d.get("footnote", "")

        if not steps:
            return self._content_slide(d)

        # Build step blocks with arrows between them
        step_blocks = []
        for i, step in enumerate(steps):
            num = step.get("number", str(i + 1))
            step_title = _esc(step.get("title", ""))
            desc = _esc(step.get("desc", ""))

            block_str = f"""block(
        fill: {_rgb(t['card_fill'])},
        stroke: 0.75pt + {_rgb(t['border'])},
        radius: 4pt,
        inset: 10pt,
        width: 100%,
      )[
        #align(center)[
          #block(
            fill: {_rgb(t['accent'])},
            radius: 50%,
            width: 28pt,
            height: 28pt,
            inset: 4pt,
          )[#align(center + horizon, text(weight: "bold", size: 14pt, fill: {_rgb(t['title_fg'])})[{_esc(num)}])]
          #v(6pt)
          #text(weight: "bold", size: 11pt, fill: {_rgb(t['text'])})[#upper("{step_title}")]
          #v(3pt)
          #text(size: 9pt, fill: {_rgb(t['muted'])})[{desc}]
        ]
      ]"""
            step_blocks.append(block_str)

            # Add arrow between steps (not after last)
            if i < len(steps) - 1:
                step_blocks.append(
                    f'align(center + horizon, text(size: 20pt, fill: {_rgb(t["accent"])})[\\u{{2192}}])'
                )

        n_cols = len(steps) * 2 - 1  # steps + arrows
        cols = []
        for i in range(n_cols):
            cols.append("0.5fr" if i % 2 == 1 else "1fr")  # arrows get less space
        cols_str = ", ".join(cols)
        blocks_str = ",\n    ".join(step_blocks)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(1fr)

  grid(
    columns: ({cols_str}),
    gutter: 6pt,
    {blocks_str}
  )

  v(1fr)
  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Icon stat slide ---------------------------------------------------

    def _icon_stat_slide(self, d: dict) -> str:
        """Big number + emoji/icon + label — statistical infographic style.

        data: section, title, stats [{value, icon, label, desc?}], footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        stats = d.get("stats", [])
        footnote = d.get("footnote", "")

        if not stats:
            return self._content_slide(d)

        # Brand discipline: ALL stat values use the SINGLE brand accent.
        # Variation is by ICON, not by colour. A multi-coloured row of stats
        # is the visual equivalent of mixed fonts.
        stat_blocks = []
        for i, s in enumerate(stats):
            value = _esc(s.get("value", ""))
            icon = s.get("icon", "")
            label = _esc(s.get("label", ""))
            desc = _esc(s.get("desc", ""))

            # Auto-scale value font: shorter values get larger text
            val_len = len(value.replace("\\#", "#").replace("\\$", "$"))
            if val_len <= 4:
                val_size = 36
            elif val_len <= 7:
                val_size = 28
            else:
                val_size = 22

            stat_blocks.append(f"""block(
        fill: {_rgb(t['card_fill'])},
        stroke: 0.75pt + {_rgb(t['border'])},
        radius: 4pt,
        inset: 12pt,
        width: 100%,
      )[
        #align(center)[
          {f'#text(size: 24pt)[{icon}]#v(4pt)' if icon else ''}
          #text(weight: "bold", size: {val_size}pt, fill: {_rgb(t['accent'])})[{value}]
          #v(4pt)
          #text(weight: "bold", size: 9pt, fill: {_rgb(t['muted'])})[#upper("{label}")]
          {f'#v(2pt)#text(size: 8pt, fill: {_rgb(t["muted"])})[{desc}]' if desc else ''}
        ]
      ]""")

        n = len(stat_blocks)
        cols_str = ", ".join(["1fr"] * n)
        blocks_str = ",\n    ".join(stat_blocks)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(1fr)

  grid(
    columns: ({cols_str}),
    gutter: 14pt,
    {blocks_str}
  )

  v(1fr)
  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Progress bars slide -----------------------------------------------

    def _progress_bars_slide(self, d: dict) -> str:
        """Labelled percentage bars — skill bars, completion, ratings.

        data: section, title, bars [{label, pct, value?}], footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        bars = d.get("bars", [])[:self.MAX_PROGRESS_BARS]
        footnote = d.get("footnote", "")

        if not bars:
            return self._content_slide(d)

        # Brand discipline: ALL progress bars use the SINGLE brand accent
        # colour. Variation is by FILL PERCENTAGE, not hue. A roadmap is
        # one programme, not six unrelated initiatives in different colours.
        bar_rows = []
        for i, b in enumerate(bars):
            label = _esc(b.get("label", ""))
            pct = b.get("pct", 0)
            value = _esc(b.get("value", f"{pct}%"))

            bar_rows.append(f"""  grid(
    columns: (4cm, 1fr, 1.5cm),
    gutter: 8pt,
    align(right + horizon, text(size: 10pt, weight: "bold", fill: {_rgb(t['text'])})[{label}]),
    block(width: 100%, height: 16pt, fill: {_rgb(t['card_fill'])}, stroke: 0.5pt + {_rgb(t['border'])}, radius: 3pt)[
      #block(width: {pct}%, height: 100%, fill: {_rgb(t['accent'])}, radius: 3pt)[]
    ],
    align(left + horizon, text(size: 10pt, weight: "bold", fill: {_rgb(t['accent'])})[{value}]),
  )""")

        bars_str = "\n  v(4pt)\n  ".join(bar_rows)

        return f"""#{{
  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(12pt)

  {bars_str}
}}"""

    # -- Pyramid slide -----------------------------------------------------

    def _pyramid_slide(self, d: dict) -> str:
        """3-5 tier hierarchy pyramid.

        data: section, title, tiers [{label, desc?}] (top to bottom), footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        tiers = d.get("tiers", [])[:self.MAX_PYRAMID_TIERS]
        footnote = d.get("footnote", "")

        if not tiers:
            return self._content_slide(d)

        colors = t.get("chart_colors", [t["accent"]])
        n = len(tiers)
        tier_blocks = []
        for i, tier in enumerate(tiers):
            label = _esc(tier.get("label", ""))
            desc = _esc(tier.get("desc", ""))
            color = colors[i % len(colors)]
            # Each tier gets wider — top is narrowest
            width_pct = 30 + (i * (70 // n))

            tier_blocks.append(f"""  align(center, block(
    fill: {_rgb(color)},
    radius: 3pt,
    inset: (x: 12pt, y: 6pt),
    width: {width_pct}%,
  )[
    #align(center)[
      #text(weight: "bold", size: 11pt, fill: white)[#upper("{label}")]
      {f'#v(2pt)#text(size: 9pt, fill: white.transparentize(30%))[{desc}]' if desc else ''}
    ]
  ])""")

        tiers_str = "\n  v(4pt)\n".join(tier_blocks)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(1fr)

{tiers_str}

  v(1fr)
  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Comparison slide --------------------------------------------------

    def _comparison_slide(self, d: dict) -> str:
        """Structured side-by-side comparison with metrics.

        data: section, title, left {name, items [{label, value}]},
              right {name, items [{label, value}]}, footnote
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        left = d.get("left", {})
        right = d.get("right", {})
        footnote = d.get("footnote", "")

        left_name = _esc(left.get("name", "Option A"))
        right_name = _esc(right.get("name", "Option B"))
        left_items = left.get("items", [])
        right_items = right.get("items", [])

        # Build comparison rows (cap to fit on slide)
        left_items = left_items[:self.MAX_COMPARISON_ROWS]
        right_items = right_items[:self.MAX_COMPARISON_ROWS]
        rows = []
        max_rows = max(len(left_items), len(right_items))
        for i in range(max_rows):
            l_item = left_items[i] if i < len(left_items) else {}
            r_item = right_items[i] if i < len(right_items) else {}
            l_label = _esc(l_item.get("label", "") if isinstance(l_item, dict) else str(l_item))
            l_value = _esc(l_item.get("value", "") if isinstance(l_item, dict) else "")
            r_label = _esc(r_item.get("label", "") if isinstance(r_item, dict) else str(r_item))
            r_value = _esc(r_item.get("value", "") if isinstance(r_item, dict) else "")

            fill = _rgb(t['card_fill']) if i % 2 == 0 else _rgb(t['bg'])
            rows.append(f"""    grid(
      columns: (1fr, 1fr),
      gutter: 14pt,
      block(fill: {fill}, inset: 8pt, width: 100%, radius: 2pt)[
        #text(size: 10pt, fill: {_rgb(t['muted'])})[{l_label}]
        {f'#h(1fr)#text(size: 10pt, weight: "bold", fill: {_rgb(t["text"])})[{l_value}]' if l_value else ''}
      ],
      block(fill: {fill}, inset: 8pt, width: 100%, radius: 2pt)[
        #text(size: 10pt, fill: {_rgb(t['muted'])})[{r_label}]
        {f'#h(1fr)#text(size: 10pt, weight: "bold", fill: {_rgb(t["text"])})[{r_value}]' if r_value else ''}
      ],
    )""")

        rows_str = "\n    v(2pt)\n".join(rows)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(14pt)

  // Column headers
  grid(
    columns: (1fr, 1fr),
    gutter: 14pt,
    block(fill: {_rgb(t['card_fill'])}, stroke: (bottom: 2pt + {_rgb(t['accent'])}), inset: 10pt, width: 100%)[
      #align(center, text(weight: "bold", size: 14pt, fill: {_rgb(t['accent'])})[#upper("{left_name}")])
    ],
    block(fill: {_rgb(t['accent'])}, inset: 10pt, width: 100%, radius: (top: 3pt))[
      #align(center, text(weight: "bold", size: 14pt, fill: {_rgb(t['title_fg'])})[#upper("{right_name}")])
    ],
  )
  v(6pt)

  // Comparison rows
  {rows_str}

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # ==================================================================
    # MULTI-EXHIBIT SLIDE TYPES (info-dense, brochure-style)
    # ==================================================================

    # -- Feature grid (3x2 = 6 features) -----------------------------------

    def _feature_grid_slide(self, d: dict) -> str:
        """3x2 grid of feature cards with icon + title + body.

        data: section, title, features [{icon, title, body}], footnote
        Use this for: capability showcases, "what we offer", feature catalogs.
        Better than four_card when you have 5-6 items.
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        features = d.get("features", [])[:6]
        footnote = d.get("footnote", "")

        if not features:
            return self._content_slide(d)

        # Brand discipline: ALL number badges use the single brand accent
        # colour, NOT a rainbow. Best practice: 2-3 colour brand system.
        cells = []
        for i, f in enumerate(features):
            icon = f.get("icon", "")
            f_title = _esc(f.get("title", ""))
            f_body = _esc(f.get("body", ""))

            cells.append(f"""block(
        fill: {_rgb(t['card_fill'])},
        stroke: 0.75pt + {_rgb(t['border'])},
        radius: 4pt,
        inset: 12pt,
        width: 100%,
      )[
        #grid(
          columns: (auto, 1fr),
          gutter: 8pt,
          block(fill: {_rgb(t['accent'])}, radius: 50%, width: 24pt, height: 24pt, inset: 4pt)[
            #align(center + horizon, text(weight: "bold", size: 11pt, fill: white)[{i+1}])
          ],
          text(weight: "bold", size: 11pt, fill: {_rgb(t['text'])})[#upper("{f_title}")],
        )
        #v(4pt)
        #text(size: 9pt, fill: {_rgb(t['muted'])})[{f_body}]
      ]""")

        # Pad to 6 cells with empty blocks for clean grid
        while len(cells) < 6:
            cells.append('block(width: 100%)[]')

        cells_str = ",\n    ".join(cells)

        return f"""#{{
  set page(fill: {_rgb(t['bg'])})
  set text(fill: {_rgb(t['text'])})

  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(10pt)

  v(1fr)

  grid(
    columns: (1fr, 1fr, 1fr),
    gutter: 10pt,
    {cells_str}
  )

  v(1fr)

  {footer_bar(footnote, t['border'], t['muted'])}
}}"""

    # -- Dashboard slide (chart + stats + bullets) -------------------------

    def _dashboard_slide(self, d: dict) -> str:
        """Multi-exhibit slide: chart image (left 60%) + stats stack (right 40%).

        data: section, title, image_path, stats [{value, label}], bullets [str], footnote
        The brochure-style "everything on one page" layout.
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        image_path = d.get("image_path", "")
        stats = d.get("stats", [])[:3]
        bullets = d.get("bullets", [])[:4]
        footnote = d.get("footnote", "")

        # Build stat blocks for the right column (compact for dashboard layout)
        stat_blocks = []
        for s in stats:
            stat_blocks.append(f"""block(
        fill: {_rgb(t['card_fill'])},
        stroke: (left: 3pt + {_rgb(t['accent'])}),
        inset: 8pt,
        width: 100%,
      )[
        #text(weight: "bold", size: 18pt, fill: {_rgb(t['accent'])})[{_esc(s.get('value', ''))}]
        #h(8pt)
        #text(size: 8pt, fill: {_rgb(t['muted'])})[#upper("{_esc(s.get('label', ''))}")]
      ]""")

        # Limit bullets to 3 to ensure right column fits
        bullets = bullets[:3]
        bullets_str = "\n        ".join(f"- {_esc(b)}" for b in bullets)
        stats_str = ",\n      ".join(stat_blocks) if stat_blocks else 'block()[]'

        return f"""#{{
  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(8pt)

  grid(
    columns: (1.55fr, 1fr),
    gutter: 14pt,
    // Left: chart image (compact to fit alongside dense right column)
    block(width: 100%)[
      #align(center + horizon, image("{image_path}", width: 100%, height: 6.2cm))
    ],
    // Right: stats stack + bullets (capped at 3 bullets)
    block(width: 100%)[
      #stack(
        spacing: 4pt,
        {stats_str}
      )
      {f'#v(6pt)#text(size: 8pt, fill: {_rgb(t["text"])})[{chr(10)}        {bullets_str}{chr(10)}      ]' if bullets else ''}
    ],
  )
}}"""

    # -- Chart slide with side caption -------------------------------------

    def _chart_caption_slide(self, d: dict) -> str:
        """Embedded chart image (left 65%) + supporting bullets (right 35%).

        data: section, title, image_path, caption, bullets [str], footnote
        Use this when a chart needs context — better than bare chart slide.
        """
        t = self.t
        section = d.get("section", "")
        title = d.get("title", "")
        image_path = d.get("image_path", "")
        caption = _esc(d.get("caption", ""))
        bullets = d.get("bullets", [])[:5]
        footnote = d.get("footnote", "")

        bullets_str = "\n        ".join(f"- {_esc(b)}" for b in bullets)

        return f"""#{{
  {section_badge(section, t['muted'])}
  v(6pt)
  {slide_title(title, t['text'])}
  v(10pt)

  grid(
    columns: (2.2fr, 1fr),
    rows: (7.5cm,),
    gutter: 12pt,
    // Chart — fills available height, wider allocation
    block(width: 100%, height: 100%)[
      #align(center + horizon, image("{image_path}", height: 95%, width: 95%, fit: "contain"))
    ],
    // Key takeaways panel with accent left border
    block(
      fill: {_rgb(t['card_fill'])},
      stroke: (left: 4pt + {_rgb(t['accent'])}),
      inset: 10pt,
      width: 100%,
      height: 100%,
    )[
      #text(weight: "bold", size: 9pt, tracking: 1pt, fill: {_rgb(t['accent'])})[#upper("Key takeaways")]
      #v(6pt)
      #text(size: 8.5pt, fill: {_rgb(t['text'])})[
        {bullets_str}
      ]
      {f'#v(4pt)#text(size: 7pt, style: "italic", fill: {_rgb(t["muted"])})[{caption}]' if caption else ''}
    ],
  )
}}"""


def _esc(text: str) -> str:
    """Escape special Typst characters."""
    if not text:
        return ""
    return (
        text
        .replace("\\", "\\\\")
        .replace("#", "\\#")
        .replace("$", "\\$")
        .replace("@", "\\@")
        .replace("<", "\\<")
        .replace(">", "\\>")
    )
