"""Build B — LLM-DRIVEN Inkline pitch document + slidepack via DesignAdvisor.

Same raw content sections as Build A. But Inkline's DesignAdvisor (LLM mode)
picks the slide types, action titles, layout flow, and visual hierarchy.
The document markdown is generated by Claude as well.

This is the "let the product market itself" build — the user's exact ask.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "src"))

from inkline.intelligence import DesignAdvisor
from inkline.typst import export_typst_slides, export_typst_document

OUT = ROOT / "output" / "pitch_compare"
OUT.mkdir(parents=True, exist_ok=True)

BRAND = "minimal"
TEMPLATE = "pitch"  # The new "pitch" template — bold hero stats, clean white

# Source key from Aigis env if available
if not os.environ.get("ANTHROPIC_API_KEY"):
    aigis_env = Path("/mnt/d/aigis-agents-v2/.env")
    if aigis_env.exists():
        for line in aigis_env.read_text().splitlines():
            if line.startswith("ANTHROPIC_API_KEY="):
                os.environ["ANTHROPIC_API_KEY"] = line.split("=", 1)[1].strip()
                break


# ---------------------------------------------------------------------------
# RAW CONTENT — same source material as Build A, no layout decisions
# ---------------------------------------------------------------------------

SECTIONS = [
    {
        "section": "The Problem",
        "title": "Branded output is broken",
        "type": "comparison",
        "narrative": "Three pain points that every analyst, founder, and AI builder hits when shipping branded documents and decks at scale.",
        "cards": [
            {"title": "Inconsistent decks",
             "body": "Logos stretch, fonts drift, chart palettes wander. Brand guides exist on paper, not in output."},
            {"title": "80% in PowerPoint",
             "body": "Analysts spend the bulk of their week formatting slides instead of analysing data."},
            {"title": "AI agents make ugly output",
             "body": "Your LLM produces brilliant analysis, then dumps it as raw markdown. The render layer was missing."},
        ],
    },
    {
        "section": "The Solution",
        "title": "Inkline by the numbers",
        "type": "kpi_dashboard",
        "narrative": "One Python API. Zero design decisions for the caller. Publication-quality PDF in milliseconds.",
        "metrics": {
            "Slide Layouts": "20",
            "Chart Types": "11",
            "Themes": "90+",
            "Output Formats": "6",
        },
    },
    {
        "section": "How It Works",
        "title": "Three steps from data to PDF",
        "type": "process_flow",
        "narrative": "Describe content as structured Python sections. The intelligence layer picks the right layout and chart. Typst compiles to publication-quality PDF in under two seconds.",
        "steps": [
            {"number": "1", "title": "Describe", "desc": "Pass structured content sections — metrics, narrative, comparisons, tables."},
            {"number": "2", "title": "Design", "desc": "AI advisor uses MBB design playbooks to pick layouts, charts, and visual hierarchy."},
            {"number": "3", "title": "Render", "desc": "Compiles via Typst (Rust) to embedded-font PDF in under two seconds."},
        ],
    },
    {
        "section": "Capabilities",
        "title": "Four engines, one render layer",
        "type": "comparison",
        "cards": [
            {"title": "Typst PDF backend", "body": "Rust-based, deterministic, embedded fonts, sub-2-second compilation."},
            {"title": "DesignAdvisor", "body": "LLM-driven layout selection backed by curated design playbooks."},
            {"title": "Chart renderer", "body": "11 matplotlib chart types with brand-aware styling."},
            {"title": "Brand plugin system", "body": "Public package + private brand directory. Proprietary assets never touch source."},
        ],
    },
    {
        "section": "Who It's For",
        "title": "Six audiences, one render layer",
        "type": "comparison",
        "cards": [
            {"title": "Private equity & VC", "body": "Deal-room data into IC memos and LP updates in minutes."},
            {"title": "Management consultants", "body": "McKinsey-style decks without a visual designer."},
            {"title": "Founders pitching", "body": "Tier-1 investor decks on demand, in your brand."},
            {"title": "Analysts & researchers", "body": "Publication-quality reports with embedded charts."},
            {"title": "RevOps teams", "body": "Automated monthly briefings with consistent branding."},
            {"title": "AI agent builders", "body": "The render layer LangChain and CrewAI agents have been missing."},
        ],
    },
    {
        "section": "Compare & Contrast",
        "title": "Inkline vs the alternatives",
        "type": "financial_overview",
        "table_data": {
            "headers": ["Feature", "Inkline", "PowerPoint", "Gamma", "Beautiful.ai", "python-pptx", "Slidev"],
            "rows": [
                ["Brand lock (enforced)",        "Yes",     "No",        "Partial", "Partial", "No",  "Partial"],
                ["Publication-quality PDF",      "Yes",     "Partial",   "Partial", "Partial", "Partial", "Yes"],
                ["LLM design advisor",           "Yes",     "No",        "Yes",     "Yes",     "No",  "No"],
                ["Overflow audit",               "Yes",     "No",        "No",      "Partial", "No",  "No"],
                ["Python API (agent-friendly)",  "Yes",     "No",        "No",      "No",      "Yes", "No"],
                ["Built-in chart library",       "11 types","Partial",   "Partial", "Partial", "No",  "No"],
                ["Self-hosted, no vendor lock",  "Yes",     "No",        "No",      "No",      "Yes", "Yes"],
                ["Licence",                      "MIT",     "Commercial","SaaS",    "SaaS",    "MIT", "MIT"],
            ],
        },
        "footnote": "Inkline is the only open-source toolkit combining brand lock, LLM design intelligence, and a Python-native API.",
    },
    {
        "section": "Why Inkline Wins",
        "title": "Three reasons teams switch",
        "type": "comparison",
        "cards": [
            {"title": "Brand-first by design",
             "body": "Consistency is a hard constraint. Your brand cannot be broken by a careless analyst or hallucinating LLM."},
            {"title": "Built for agents",
             "body": "Native Python API. LangChain, CrewAI, custom agents — all plug in as the rendering step."},
            {"title": "Open and extensible",
             "body": "MIT licensed. Self-hosted. Plugin-based brand system. No vendor lock-in."},
        ],
    },
    {
        "section": "Roadmap",
        "title": "Where Inkline is going",
        "type": "comparison",
        "items": [
            "Industry themes — healthcare, legal, energy, real estate",
            "LLM storyboarding — slide-to-slide narrative flow",
            "Keynote export — native .key file output",
            "Diagram integration — Mermaid, Graphviz, sequence diagrams",
            "Live preview server — interactive web preview during development",
        ],
    },
]


def build_slides_via_llm():
    """Use DesignAdvisor LLM mode to design the slidepack.

    Pre-renders chart PNGs and tells the LLM which image_paths it can use,
    so it can request chart_caption and dashboard slides.
    """
    # Pre-render the same chart set as Build A so the LLM can reference them
    from inkline.typst.chart_renderer import render_chart_for_brand

    charts_dir = OUT / "charts"
    charts_dir.mkdir(parents=True, exist_ok=True)

    # Each chart spec carries (chart_type, data, illustrative, description, color_mode)
    CC_W, CC_H = 7.0, 3.0  # chart_caption layout
    DB_W, DB_H = 6.5, 3.4  # dashboard layout

    chart_specs = {
        "time_saved.png": {
            "type": "line_chart",
            "data": {
                "x": ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"],
                "series": [
                    {"name": "Traditional (PowerPoint)", "values": [4, 8, 12, 16, 20]},
                    {"name": "Inkline", "values": [0.5, 0.5, 0.5, 0.5, 0.5]},
                ],
                "x_label": "Day", "y_label": "Hours on slides",
                "illustrative": True,
            },
            "desc": "ILLUSTRATIVE line chart showing time-saved comparison (synthetic timing data, NOT from real benchmarks). Use only with explicit ILLUSTRATIVE caption.",
            "width": CC_W, "height": CC_H, "color_mode": "duo",
        },
        "capabilities.png": {
            "type": "donut",
            "data": {
                "segments": [
                    {"label": "Slide layouts", "value": 20},
                    {"label": "Chart types", "value": 11},
                    {"label": "Themes", "value": 90},
                    {"label": "Output formats", "value": 6},
                ],
                "center_label": "Inkline\nv0.2",
            },
            "desc": "REAL donut showing Inkline v0.2 capability counts (20/11/90/6 are factual). Safe to cite directly.",
            "width": DB_W, "height": DB_H, "color_mode": "mono",
        },
        "adoption.png": {
            "type": "area_chart",
            "data": {
                "x": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
                "series": [{"name": "Stars", "values": [10, 45, 120, 280, 540, 920]}],
                "illustrative": True,
            },
            "desc": "ILLUSTRATIVE area chart (NOT real GitHub data, hypothetical adoption curve). Caption MUST say illustrative.",
            "width": CC_W, "height": CC_H, "color_mode": "mono",
        },
        "radar.png": {
            "type": "radar",
            "data": {
                "axes": ["Brand Lock", "PDF Quality", "AI Design", "Python API", "Open Source", "Charts"],
                "series": [
                    {"name": "Inkline",     "values": [95, 90, 85, 100, 100, 90]},
                    {"name": "Gamma",       "values": [50, 65, 90, 0, 0, 60]},
                    {"name": "PowerPoint",  "values": [40, 70, 0, 0, 0, 60]},
                ],
                "illustrative": True,
            },
            "desc": "ILLUSTRATIVE radar comparing Inkline/Gamma/PowerPoint (subjective ratings based on public docs). Caption must mark as illustrative.",
            "width": 4.5, "height": 4.0, "color_mode": "palette",
        },
        "savings.png": {
            "type": "waterfall",
            "data": {
                "items": [
                    {"label": "Manual cost", "value": 200, "total": True},
                    {"label": "Designer", "value": -80},
                    {"label": "Analyst time", "value": -90},
                    {"label": "Revisions", "value": -25},
                    {"label": "Inkline cost", "value": 5, "total": True},
                ],
                "illustrative": True,
            },
            "desc": "ILLUSTRATIVE waterfall — per-deck cost MODEL based on typical analyst rates ($50/hr × 4hr = $200 baseline). NOT real customer data. Caption must mark as illustrative.",
            "width": CC_W, "height": CC_H, "color_mode": "duo",
        },
    }

    chart_descriptions = []
    for filename, spec in chart_specs.items():
        render_chart_for_brand(
            spec["type"], spec["data"], str(charts_dir / filename),
            brand_name=BRAND,
            width=spec["width"], height=spec["height"],
            color_mode=spec["color_mode"],
        )
        marker = "[ILLUSTRATIVE]" if spec["data"].get("illustrative") else "[REAL DATA]"
        chart_descriptions.append(f"  - charts/{filename} {marker}: {spec['desc']}")

    chart_catalog = "\n".join(chart_descriptions)
    print(f"  Pre-rendered {len(chart_specs)} chart PNGs for LLM to reference")

    advisor = DesignAdvisor(brand=BRAND, template=TEMPLATE, mode="llm")

    # Inject chart catalog + extra-strong visual instructions into the goal field
    enriched_goal = (
        "Build a fresh, B2C, GitHub-friendly pitch for Inkline (open-source Python "
        "toolkit) that excites developers, AI builders, and analysts. Target audience "
        "is technical but not deep-technical — they want to see what it CAN DO, not how. "
        "This deck will live on a public GitHub README so it MUST be visually compelling, "
        "info-dense without being text-heavy, and showcase Inkline's range. "
        "\n\n"
        "MANDATORY: Use these slide types AT LEAST ONCE each: icon_stat, feature_grid, "
        "dashboard, chart_caption, process_flow, progress_bars. AVOID 'content' (bullets) "
        "entirely if possible. Every numerical claim should be hero-formatted. "
        "Tables MAX 5 columns × 6 rows. "
        "\n\n"
        "ABSOLUTELY FORBIDDEN (zero-tolerance hallucination rules):\n"
        "- DO NOT invent customer counts, GitHub stars, ARR figures, NRR, growth\n"
        "  rates, contributor counts, monthly downloads, or ANY metric that is\n"
        "  not in the input sections.\n"
        "- DO NOT invent source attributions like 'based on internal timing studies'\n"
        "  or 'across 50+ decks' or 'from beta customer interviews'. If the input\n"
        "  has no source, the slide has no source.\n"
        "- DO NOT name fictional customers or design partners (no 'Acme Corp',\n"
        "  no '3 YC companies', no 'Fortune 500 enterprises').\n"
        "\n"
        "ILLUSTRATIVE CHART HANDLING:\n"
        "Each chart in the catalog below is tagged [REAL DATA] or [ILLUSTRATIVE].\n"
        "When you use a chart tagged [ILLUSTRATIVE], the slide MUST:\n"
        "  1. Set the caption field to start with 'ILLUSTRATIVE — '\n"
        "  2. Include in the footnote: 'Illustrative example, not real data'\n"
        "  3. The chart_renderer adds an ILLUSTRATIVE watermark automatically.\n"
        "Charts tagged [REAL DATA] use FACTUAL Inkline counts (slide layouts, chart\n"
        "types, themes, etc.) and can be cited directly.\n"
        "\n"
        "AVAILABLE PRE-RENDERED CHART IMAGES (use exact image_path strings):\n"
        f"{chart_catalog}\n"
        "\n"
        "When a slide uses chart_caption or dashboard, use one of these chart files. "
        "For dashboard slides, ALWAYS pair the chart with 2-3 stat callouts and 3-4 "
        "supporting bullets — this is the showcase layout. "
    )

    slides = advisor.design_deck(
        title="Inkline",
        sections=SECTIONS,
        date="April 2026",
        subtitle="Branded documents and decks for teams who'd rather ship than format",
        audience="Open source developers, AI/agent builders, and analysts browsing GitHub",
        goal=enriched_goal,
        contact={
            "name": "pip install \"inkline[all]\"",
            "role": "github.com/u3126117/inkline",
            "email": "MIT licensed  ·  open source  ·  agent-ready",
            "company": "Inkline",
            "tagline": "Because your output should be as good as your analysis",
        },
    )
    return slides


def build_document_markdown_via_llm():
    """Have Claude generate the structured markdown for the pitch document."""
    import anthropic

    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    system = (
        "You are writing a B2C pitch document for Inkline — an open-source Python "
        "toolkit that lives on a public GitHub README. Target audience: open source "
        "developers, AI builders, analysts. They want FRESH and EXCITING, not boring "
        "startup pitch deck prose.\n\n"
        "PRIORITIES:\n"
        "1. INFO-DENSE BUT NOT TEXT-HEAVY. Use tables, bullet lists, and short "
        "   sentences. Avoid paragraphs longer than 3 lines.\n"
        "2. SHOW NUMBERS, NOT CLAIMS. Hero stats, comparison tables, concrete data.\n"
        "3. SCANNABLE in 30 seconds. A reader should grok the value in one minute.\n"
        "4. PUNCHY action headings — state the conclusion, not the topic.\n"
        "5. Compare/contrast table is the centrepiece. Make it tight (max 5 columns).\n\n"
        "Output STRUCTURED MARKDOWN that uses:\n"
        "- # for the document title\n"
        "- ## for top-level sections (use action headings)\n"
        "- ### for subsections\n"
        "- **bold** for emphasis on key terms and numbers\n"
        "- Tables (pipe format) for ALL structured comparisons — prefer tables to prose\n"
        "- Bulleted lists for enumerations (5-10 words each, telegraphic)\n"
        "- Fenced code blocks for code examples\n"
        "- Horizontal rules (---) between major sections\n\n"
        "MUST INCLUDE:\n"
        "- A 1-2 sentence opening hook\n"
        "- A 'by the numbers' section (table of capability counts)\n"
        "- The compare/contrast table from input (use exactly the data provided)\n"
        "- A 60-second code demo (Python, in fenced block)\n"
        "- Who-it's-for as a bulleted list (one line each)\n"
        "- Roadmap as a bulleted list with versions\n"
        "- Strong closing call to action with the install command\n\n"
        "AVOID: long paragraphs, marketing fluff, repetition, '1.5x faster' style claims "
        "without specifics. Be specific or be silent.\n\n"
        "Output ONLY the markdown content, no preamble or commentary."
    )

    user = """Write a pitch document for Inkline. Use this raw material:

PRODUCT: Inkline — a Python toolkit that turns structured data into investor-ready
decks, due-diligence reports, and executive briefings — automatically, in your brand.

KEY NUMBERS: 17 slide layouts, 11 chart types, 90+ themes, 6 output formats, MIT licensed.

PROBLEMS IT SOLVES:
- Inconsistent branded decks (logos stretch, fonts drift)
- Analysts spend 80% of time in PowerPoint, not analysing
- AI agents produce brilliant analysis but ugly output
- Slide content keeps overflowing
- No designer available for every report
- Proprietary brands cannot be committed to public repos

WHO IT'S FOR:
- Private equity & VC (deal-room data → IC memos)
- Management consultants (McKinsey-style decks without a designer)
- Founders pitching (tier-1 investor decks on demand)
- Analysts & researchers (publication-quality reports)
- RevOps teams (automated monthly briefings)
- AI agent builders (the render layer LangChain/CrewAI need)

HOW IT WORKS: Three steps — Describe (structured Python sections) → Design (AI
advisor picks layouts using MBB playbooks) → Render (Typst compiles to PDF in
under 2 seconds).

UNDER THE HOOD: Typst (Rust-based PDF), matplotlib (charts), Anthropic Claude
(optional LLM design intelligence), plugin-based brand discovery from
~/.config/inkline/brands/.

COMPARE & CONTRAST TABLE (use this exact data):
| Feature | Inkline | PowerPoint | Gamma | Beautiful.ai | python-pptx | Slidev |
|---------|---------|------------|-------|--------------|-------------|--------|
| Brand lock (enforced) | Yes | No | Partial | Partial | No | Partial |
| Publication-quality PDF | Yes | Partial | Partial | Partial | Partial | Yes |
| LLM design advisor | Yes | No | Yes | Yes | No | No |
| Overflow audit | Yes | No | No | Partial | No | No |
| Python API (agent-friendly) | Yes | No | No | No | Yes | No |
| Built-in chart library | 11 types | Partial | Partial | Partial | No | No |
| Self-hosted, no vendor lock | Yes | No | No | No | Yes | Yes |
| Licence | MIT | Commercial | SaaS | SaaS | MIT | MIT |

CODE DEMO (use something like this):
```python
from inkline.typst import export_typst_slides
export_typst_slides(slides=[...], output_path="deck.pdf", brand="minimal")
```

ROADMAP: industry themes, LLM storyboarding, Keynote export, diagram integration,
live preview server.

INSTALL: pip install "inkline[all] @ git+https://github.com/u3126117/inkline.git"

TAGLINE: "Because your output should be as good as your analysis."

Now write the full pitch document."""

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4096,
        system=system,
        messages=[{"role": "user", "content": user}],
    )

    return response.content[0].text


def main():
    print("=" * 70)
    print("BUILD B — LLM-DRIVEN")
    print("=" * 70)

    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("\nERROR: ANTHROPIC_API_KEY not set. Cannot run LLM mode.")
        sys.exit(1)

    # Slidepack — let DesignAdvisor pick everything
    print("\n[1/2] Designing slidepack via DesignAdvisor (LLM mode)...")
    slides = build_slides_via_llm()

    print(f"\n  DesignAdvisor planned {len(slides)} slides:")
    for i, s in enumerate(slides):
        title = s["data"].get("title", s["data"].get("company", ""))
        print(f"    {i+1:2d}. [{s['slide_type']:12s}] {title[:60]}")

    # Save slide specs
    spec_path = OUT / "pitch_slides_llm.json"
    spec_path.write_text(json.dumps(slides, indent=2, default=str), encoding="utf-8")

    slides_path = OUT / "pitch_slides_llm.pdf"
    export_typst_slides(
        slides=slides,
        output_path=str(slides_path),
        brand=BRAND,
        template=TEMPLATE,
        title="Inkline",
        date="April 2026",
        subtitle="The branded document engine",
    )
    print(f"\n  PDF: {slides_path} ({slides_path.stat().st_size:,} bytes)")

    # Document — let Claude generate the markdown
    print("\n[2/2] Generating pitch document markdown via Claude...")
    md = build_document_markdown_via_llm()

    md_path = OUT / "pitch_doc_llm.md"
    md_path.write_text(md, encoding="utf-8")
    print(f"  Markdown: {md_path} ({len(md)} chars, {md.count(chr(10))} lines)")

    doc_path = OUT / "pitch_doc_llm.pdf"
    export_typst_document(
        markdown=md,
        output_path=str(doc_path),
        brand=BRAND,
        title="Inkline",
        subtitle="The branded document engine",
        date="April 2026",
        author="Designed by Inkline DesignAdvisor (LLM mode)",
        paper="a4",
    )
    print(f"  PDF: {doc_path} ({doc_path.stat().st_size:,} bytes)")

    print(f"\n  Brand: {BRAND}  ·  Template: {TEMPLATE}  ·  Mode: LLM-driven")


if __name__ == "__main__":
    main()
